hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - data: ikonos
  - tokenizer: cosmos_f8c16p4_lora
  # self ============
  - _self_
  # hydra overrides ====
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# set tokenizer to null
tokenizer: null

total_bands_of_sensors:
  WV2: 8
  WV3: 8
  WV4: 4
  IKONOS: 4
  MMSeg_YREB: 12
  DCF_2019: 8

processor:
  ratio: 4
  sensor: IKONOS
  pan_weights: mean # Or a list e.g., [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125]
  downsample_type: avgpool
  nbands: ${total_bands_of_sensors.${processor.sensor}}
  upsample_type: bilinear

consts:
  sensor: ${processor.sensor}
  total_bands_of_sensors: ${total_bands_of_sensors.${processor.sensor}}
  ratio: ${processor.ratio}
  nbands: ${total_bands_of_sensors.${processor.sensor}}
  tokenizer_checkpoint_path:
  run_device: 1
  to_neg_1_1: ${data.to_neg_1_1}
  tar_file_name: Pansharpening_${processor.sensor}.tar

output:
  output_dir: data/IKONOS
  maxsize: 4.0e9
