hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  # wrapper ==========
  - dataset: mat_singles
  - accelerator: base
  - model@segment_model: tokenizer_hybrid_decoder
  # self ===============
  - _self_

  # hydra overrides ====
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

ema:
  _target_: ema_pytorch.EMA
  _partial_: true
  beta: 0.995
  update_after_step: 1000
  update_every: 3
  allow_different_devices: true
  lazy_init_ema: true

metric:
  _target_: src.stage2.segmentation.metrics.basic.HyperSegmentationScore
  n_classes: ${dataset.consts.num_classes}
  ignore_index: 255
  include_bg: false
  input_format: index
  task: multiclass

train:
  # Wrapper-based training
  val_slide_window: true
  grad_check: false
  act_checkpoint: true
  val_slide_window_kwargs:
    patch_size: 128 #${dataset.consts.patch_size}
    stride: 32 #${dataset.consts.stride}

  use_single_img_indexing: false
  patches_per_image:
  macro_batch_size: 32

  proj_dir: runs/stage2_classification/
  finetune_strategy: finetune_all
  max_grad_norm: 1.0

  track_metrics_duration: -1
  track_metrics_after: 2000
  visualize_every: 500
  max_steps: 40_000
  save_every: 500
  is_neg_1_1: true

  resume_path:
  ema_load_path:

  segment_optim:
    _target_: heavyball.ForeachAdamW
    _partial_: true
    lr: 4.0e-4
    weight_decay: 0.0
    betas: ${tuple:[0.9, 0.95]} #[0.5, 0.9], gan training beta1 is zero
    caution: true
    foreach: true

    # _target_: src.utilities.optim.MuonFSDP.create_muon_optimizer
    # _partial_: true
    # betas: [0.95, 0.99]
    # oned_param_algo: lion
    # use_triton: true
    # muon_params_defaults:
    #   lr: 6.0e-4
    #   weight_decay: 0.01
    # oned_params_defaults:
    #   lr: 6.0e-4
    #   weight_decay: 0.0

  segment_sched:
    _target_: transformers.optimization.get_cosine_schedule_with_warmup
    _partial_: true
    num_warmup_steps: 0
    num_training_steps: ${train.max_steps}
    num_cycles: 3

  segment_loss:
    _target_: src.stage2.segmentation.loss.seg_loss.HyperSegmentationLoss
    ignore_index: 255
    ce_weight: null
    loss_weights: [1.0, 1.0, 0.5]
    mode: multiclass

  log:
    run_comment: ${dataset.dataset_name}_tokenizer_hybrid_adaptor
    log_with_time: true
    log_every: 10
  debug: true

val:
  val_duration: 50
  max_val_iters: -1
