hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - dataset: sos_oil_leakage_sentinel
  - accelerator: base
  - model@segment_model: tokenizer_hybrid_decoder
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

segment_model:
  tokenizer_feature:
    features_per_stage: [384, 384, 384, 384]
    conv_inplane: 64
    drop_path_rate: 0.1
    cffn_ratio: 0.5
    deform_ratio: 0.5

  adapter:
    depth_per_stage: 2
    n_conv_per_stage: 2
    drop: 0.2

ema:
  _target_: ema_pytorch.EMA
  _partial_: true
  beta: 0.995
  update_after_step: 1000
  update_every: 2
  allow_different_devices: true
  lazy_init_ema: true

metric:
  _target_: src.stage2.segmentation.metrics.basic.HyperSegmentationScore
  n_classes: ${dataset.consts.num_classes}
  ignore_index: null
  include_bg: true
  input_format: index
  task: multiclass

train:
  val_slide_window: false
  grad_check: false
  act_checkpoint: true
  vis_rgb_channels: ${dataset.consts.rgb_bands}
  val_slide_window_kwargs:
    patch_size: ${dataset.consts.img_size}
    stride: 64

  use_single_img_indexing: false
  patches_per_image:
  macro_batch_size: 2

  proj_dir: runs/stage2_segmentation/
  finetune_strategy: finetune_all
  max_grad_norm: 1.0

  track_metrics_duration: -1
  track_metrics_after: 1000
  visualize_every: 200
  max_steps: 20_000
  save_every: 500
  is_neg_1_1: ${dataset.to_neg_1_1}

  resume_path:
  ema_load_path: runs/stage2_segmentation/2026-02-09_19-28-22_SOS-OilLeakage-Sentinel_hybrid_tokenizer/ema

  bootstrap_ratio: 0.0
  bootstrap_start_step: 0

  segment_optim:
    _target_: src.utilities.optim.MuonFSDP.create_muon_optimizer
    _partial_: true
    betas: [0.95, 0.99]
    oned_param_algo: lion
    muon_params_defaults:
      lr: 2.0e-4
      weight_decay: 0.01
    oned_params_defaults:
      lr: 2.0e-4
      weight_decay: 0.0

  segment_sched:
    _target_: transformers.optimization.get_cosine_schedule_with_warmup
    _partial_: true
    num_warmup_steps: 0
    num_training_steps: ${train.max_steps}
    num_cycles: 2

  segment_loss:
    _target_: src.stage2.segmentation.loss.seg_loss.HyperSegmentationLoss
    num_classes: ${dataset.consts.num_classes}
    ignore_index: ${dataset.consts.ignore_index}
    ce_weight: null #[0.1, 2.0]
    loss_weights: [1.0, 3.0, 0.0, 0.0]
    mode: multiclass
    dynamic_mode: null
    ema_decay: 0.99

  log:
    run_comment: ${dataset.dataset_name}_hybrid_tokenizer
    log_with_time: true
    log_every: 10
    log_with: [wandb]
  debug: true

val:
  val_duration: 40
  max_val_iters: -1
