repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.3.4"
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^(docs/|tests/|src/stage2/generative/maskbit)
      - id: ruff-format
        exclude: ^(docs/|tests/|src/stage2/generative/maskbit)
