_target_: src.stage1.utilities.VQLPIPSWithDiscriminator
disc_network_type: patchgan # [patchgan, patchgan_v2, stylegan]
disc_ndf: 128
use_actnorm: false
disc_input_size: ${dataset.img_size}
disc_in_channels: ${dataset.channels}
# perceptual
perceptual_weight: 0.1
perceptual_type: remote_clip_RN50
perceptual_groups_to_select: 0.5
perceptual_loss_on_logits: false
gram_model: null
gram_loss_weight: 50000.0
# ssim loss
loss_ssim: true
ssim_weight: 0.1
# lecam
lecam_loss_weight: 0.001
# recon loss
reconstruction_weight: 4.0
reconstruction_loss_type: l1
force_not_use_recon_loss: false # compute the reconstruction loss outside
# gen and disc losses
gen_loss_weight: null
disc_weight: 0.08 # weight on g_loss
disc_start_for_g: 0
disc_start_for_d: 500
disc_reg_r1: 10
disc_reg_freq: 0 # 0 means disabled
disc_loss: hinge
# quantizer
quantizer_type: null
quantizer_options:
  quantizer_loss_weight: 0.1
  codebook_enlarge_ratio: 3.0
  codebook_enlarge_steps: 2000
perceptual_options:
  clip_model_ckpt_path: src/stage1/utilities/losses/remote_clip_v2/checkpoint/RemoteCLIP-RN50.pt
