from __future__ import annotations

import argparse
import json
import math
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import torch
from PIL import Image, ImageDraw

CURRENT_FILE = Path(__file__).resolve()
SANA_ROOT = CURRENT_FILE.parents[1]
PROJECT_ROOT = CURRENT_FILE.parents[5]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
if str(SANA_ROOT) not in sys.path:
    sys.path.insert(0, str(SANA_ROOT))

from src.utilities.train_utils import get_rgb_image


@dataclass(slots=True)
class SampleRecord:
    dataset_index: int
    dataset_key: str
    sampler: str
    cfg_ratio: float
    generated_path: Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Visualize HSIGene GT-vs-generated RGB pairs into one grid image.")
    parser.add_argument(
        "--metadata-jsonl",
        type=Path,
        default=Path("src/stage2/generative/Sana/outputs_hsigene_infer/metadata.jsonl"),
        help="Metadata jsonl generated by infer_HSIGene.py.",
    )
    parser.add_argument(
        "--real-litdata-dir",
        type=str,
        default="data2/HSIGene_dataset/LitData_hyper_images/test",
        help="LitData directory containing HSIGene test real images.",
    )
    parser.add_argument(
        "--output-file",
        type=Path,
        default=Path("src/stage2/generative/Sana/outputs_hsigene_infer/gt_vs_gen_grid.png"),
        help="Output grid image path.",
    )
    parser.add_argument("--sampler", type=str, default="all", help="Filter by sampler, or `all`.")
    parser.add_argument("--cfg-ratio", type=str, default="all", help="Filter by cfg ratio (e.g. 4.5), or `all`.")
    parser.add_argument("--max-samples", type=int, default=64, help="Max number of pairs shown in grid.")
    parser.add_argument("--start-index", type=int, default=0, help="Start offset in filtered records.")
    parser.add_argument("--thumb-size", type=int, default=256, help="Size of each RGB thumbnail.")
    parser.add_argument("--pairs-per-row", type=int, default=4, help="Number of pairs per row.")
    parser.add_argument("--outer-gap", type=int, default=14, help="Gap between pairs.")
    parser.add_argument("--inner-gap", type=int, default=8, help="Gap between GT and generated image in a pair.")
    parser.add_argument(
        "--rgb-bands",
        type=str,
        default="20,12,4",
        help="Bands for GT HSI->RGB, e.g. 20,12,4 or mean/largest/std/entropy/low_correlation.",
    )
    parser.add_argument(
        "--rgb-use-linstretch",
        action="store_true",
        default=True,
        help="Apply linear stretch when converting GT HSI to RGB.",
    )
    parser.add_argument("--no-rgb-use-linstretch", action="store_false", dest="rgb_use_linstretch")
    parser.add_argument("--strict-key-check", action="store_true", help="Raise error when real key != metadata key.")
    return parser.parse_args()


def parse_rgb_bands(raw: str) -> list[int] | str:
    value = raw.strip()
    if not value:
        return "mean"
    lowered = value.lower()
    if lowered in {"mean", "largest", "std", "entropy", "low_correlation"}:
        return lowered
    bands = [int(part.strip()) for part in value.split(",") if part.strip()]
    if len(bands) != 3:
        raise ValueError(f"`--rgb-bands` expects 3 integers or named strategy, got: {raw}")
    return bands


def resolve_path(path_str: str) -> str:
    path = Path(path_str)
    if path.is_absolute() or path.exists():
        return str(path)
    sana_path = SANA_ROOT / path
    if sana_path.exists():
        return str(sana_path)
    project_path = PROJECT_ROOT / path
    if project_path.exists():
        return str(project_path)
    return str(path)


def safe_name(name: str) -> str:
    cleaned = re.sub(r"[^0-9A-Za-z._-]+", "_", name).strip("._")
    return cleaned if cleaned else "sample"


def normalize_key(raw_key: Any) -> str:
    if isinstance(raw_key, (list, tuple)):
        value = str(raw_key[0]) if raw_key else ""
    else:
        value = str(raw_key)
    return safe_name(value)


def _parse_cfg_ratio_filter(cfg_ratio: str) -> float | None:
    if cfg_ratio.strip().lower() == "all":
        return None
    return float(cfg_ratio)


def read_records(
    metadata_jsonl: Path,
    sampler: str,
    cfg_ratio: float | None,
) -> list[SampleRecord]:
    if not metadata_jsonl.exists():
        raise FileNotFoundError(f"metadata jsonl not found: {metadata_jsonl}")

    records: list[SampleRecord] = []
    with metadata_jsonl.open("r", encoding="utf-8") as fp:
        for line in fp:
            if not line.strip():
                continue
            raw = json.loads(line)
            generated_path = Path(str(raw["output"]))
            if not generated_path.exists():
                alt_path = PROJECT_ROOT / generated_path
                if alt_path.exists():
                    generated_path = alt_path
            if not generated_path.exists():
                continue

            record = SampleRecord(
                dataset_index=int(raw["dataset_index"]),
                dataset_key=safe_name(str(raw.get("dataset_key", ""))),
                sampler=str(raw.get("sampler", "")),
                cfg_ratio=float(raw.get("cfg_ratio", 0.0)),
                generated_path=generated_path,
            )
            if sampler != "all" and record.sampler != sampler:
                continue
            if cfg_ratio is not None and abs(record.cfg_ratio - cfg_ratio) > 1e-8:
                continue
            records.append(record)
    return records


def load_litdata_dataset(real_litdata_dir: str) -> Any:
    import litdata

    import src.data.codecs  # noqa: F401

    return litdata.StreamingDataset(input_dir=real_litdata_dir)


def _to_chw_tensor(value: Any) -> torch.Tensor:
    if torch.is_tensor(value):
        tensor = value.detach().cpu()
    elif isinstance(value, np.ndarray):
        tensor = torch.from_numpy(np.array(value, copy=True))
    elif isinstance(value, Image.Image):
        tensor = torch.from_numpy(np.array(value, copy=True))
    else:
        raise TypeError(f"Unsupported image type: {type(value)}")

    if tensor.ndim == 2:
        return tensor.unsqueeze(0)
    if tensor.ndim != 3:
        raise ValueError(f"Expected 2D/3D image-like tensor, got shape={tuple(tensor.shape)}")

    h, w = int(tensor.shape[0]), int(tensor.shape[1])
    c_last = int(tensor.shape[2])
    c_first = int(tensor.shape[0])
    if c_first <= 256 and int(tensor.shape[1]) > 32 and c_last > 32:
        return tensor
    if c_last <= 256 and h > 32 and w > 32:
        return tensor.permute(2, 0, 1)
    if tensor.shape[0] <= tensor.shape[2]:
        return tensor
    return tensor.permute(2, 0, 1)


def _to_unit_interval(chw: torch.Tensor) -> torch.Tensor:
    x = chw.to(torch.float32)
    min_value = float(x.min().item())
    max_value = float(x.max().item())
    if min_value >= 0.0 and max_value <= 1.0:
        return x
    if min_value >= -1.0 and max_value <= 1.0:
        return (x + 1.0) / 2.0
    if min_value >= 0.0 and max_value <= 255.0:
        return x / 255.0
    if max_value <= min_value:
        return torch.zeros_like(x, dtype=torch.float32)
    return (x - min_value) / (max_value - min_value + 1e-8)


def _tensor_rgb_to_pil(rgb_01_chw: torch.Tensor, size: int) -> Image.Image:
    rgb_u8 = (rgb_01_chw.clamp(0.0, 1.0) * 255.0).round().to(torch.uint8)
    rgb_hwc = rgb_u8.permute(1, 2, 0).cpu().numpy()
    image = Image.fromarray(rgb_hwc, mode="RGB")
    if image.size != (size, size):
        resample = Image.Resampling.BICUBIC if hasattr(Image, "Resampling") else Image.BICUBIC
        image = image.resize((size, size), resample=resample)
    return image


def load_generated_rgb_image(path: Path, size: int) -> Image.Image:
    with Image.open(path) as image:
        rgb = image.convert("RGB")
        if rgb.size != (size, size):
            resample = Image.Resampling.BICUBIC if hasattr(Image, "Resampling") else Image.BICUBIC
            rgb = rgb.resize((size, size), resample=resample)
        return rgb.copy()


def load_real_rgb_image(
    sample: dict[str, Any], rgb_bands: list[int] | str, use_linstretch: bool, size: int
) -> Image.Image:
    if "img" not in sample:
        raise KeyError("Field `img` not found in litdata sample.")
    hsi_chw = _to_chw_tensor(sample["img"])
    hsi_01 = _to_unit_interval(hsi_chw).unsqueeze(0)
    rgb_01 = get_rgb_image(hsi_01, rgb_channels=rgb_bands, use_linstretch=use_linstretch).squeeze(0)
    return _tensor_rgb_to_pil(rgb_01, size=size)


def compose_grid(
    pairs: list[tuple[Image.Image, Image.Image, str]],
    output_file: Path,
    thumb_size: int,
    pairs_per_row: int,
    outer_gap: int,
    inner_gap: int,
) -> None:
    if not pairs:
        raise RuntimeError("No pairs to draw.")

    cols = max(1, pairs_per_row)
    rows = math.ceil(len(pairs) / cols)
    text_h = 22
    title_h = 28
    pair_w = 2 * thumb_size + inner_gap
    pair_h = thumb_size + text_h

    canvas_w = outer_gap + cols * pair_w + (cols - 1) * outer_gap + outer_gap
    canvas_h = title_h + outer_gap + rows * pair_h + (rows - 1) * outer_gap + outer_gap
    canvas = Image.new("RGB", (canvas_w, canvas_h), color=(255, 255, 255))
    draw = ImageDraw.Draw(canvas)
    draw.text((outer_gap, 6), f"HSIGene GT vs Generated | pairs={len(pairs)}", fill=(20, 20, 20))

    for index, (gt_img, gen_img, label) in enumerate(pairs):
        row = index // cols
        col = index % cols
        x = outer_gap + col * (pair_w + outer_gap)
        y = title_h + outer_gap + row * (pair_h + outer_gap)

        canvas.paste(gt_img, (x, y))
        canvas.paste(gen_img, (x + thumb_size + inner_gap, y))
        draw.text((x, y + thumb_size + 2), label, fill=(40, 40, 40))

    output_file.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(output_file)


def main() -> None:
    args = parse_args()
    rgb_bands = parse_rgb_bands(args.rgb_bands)
    cfg_ratio_filter = _parse_cfg_ratio_filter(args.cfg_ratio)
    records = read_records(
        metadata_jsonl=args.metadata_jsonl,
        sampler=args.sampler,
        cfg_ratio=cfg_ratio_filter,
    )

    start = max(0, args.start_index)
    selected = records[start:]
    if args.max_samples > 0:
        selected = selected[: args.max_samples]
    if not selected:
        raise RuntimeError("No records selected. Check filters/start-index/max-samples.")

    ds = load_litdata_dataset(resolve_path(args.real_litdata_dir))

    pairs: list[tuple[Image.Image, Image.Image, str]] = []
    for record in selected:
        sample = ds[record.dataset_index]
        if sample is None:
            continue
        if not isinstance(sample, dict):
            raise ValueError(f"Expected dict sample from litdata, got {type(sample)}")
        real_key = normalize_key(sample.get("__key__", record.dataset_index))
        if real_key != record.dataset_key:
            message = f"Key mismatch at idx={record.dataset_index}: got `{real_key}`, expected `{record.dataset_key}`"
            if args.strict_key_check:
                raise RuntimeError(message)
            print(f"[warn] {message}")

        gt_rgb = load_real_rgb_image(
            sample=sample,
            rgb_bands=rgb_bands,
            use_linstretch=args.rgb_use_linstretch,
            size=args.thumb_size,
        )
        gen_rgb = load_generated_rgb_image(record.generated_path, size=args.thumb_size)
        label = f"idx={record.dataset_index}  key={record.dataset_key}  GT|GEN"
        pairs.append((gt_rgb, gen_rgb, label))

    compose_grid(
        pairs=pairs,
        output_file=args.output_file,
        thumb_size=args.thumb_size,
        pairs_per_row=args.pairs_per_row,
        outer_gap=args.outer_gap,
        inner_gap=args.inner_gap,
    )
    print(f"Saved grid: {args.output_file}")
    print(f"Pairs visualized: {len(pairs)}")


if __name__ == "__main__":
    """
    python src/stage2/generative/Sana/infer_scripts/vis_HSIGene_gen_vs_gt.py \
    --metadata-jsonl src/stage2/generative/Sana/outputs_hsigene_infer/metadata.jsonl \
    --real-litdata-dir data2/HSIGene_dataset/LitData_hyper_images/test \
    --output-file src/stage2/generative/Sana/gt_vs_gen_grid.png \
    --max-samples 64
    """
    main()
