hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  # wrapper ==========
  - dataset: OSCD
  - accelerator: base
  - segment_model: cd_wrapper_dinov3_cosmos
  # self ===============
  - _self_

  # hydra overrides ====
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

ema:
  _target_: ema_pytorch.EMA
  _partial_: true
  beta: 0.999
  update_after_step: 1000
  update_every: 1
  allow_different_devices: true
  lazy_init_ema: true

segment_loss:
  _target_: src.stage2.segmentation.loss.seg_loss.HyperSegmentationLoss
  ignore_index: 255
  ce_weight: [1.0, 10.0]
  loss_weights: [0.5, 1.0, 0.5]

metric:
  _target_: src.stage2.change_detection.metrics.basic.ChangeDetectionScore
  n_classes: ${dataset.consts.num_classes}
  ignore_index: 255
  include_bg: false

train:
  # Wrapper-based training
  val_slide_window: true
  grad_check: false
  act_checkpoint: true

  use_single_img_indexing: false
  patches_per_image:
  macro_batch_size: 32

  proj_dir: runs/stage2_CD_wrapper/
  finetune_strategy: finetune_all
  max_grad_norm: 0.03

  track_metrics_duration: -1
  track_metrics_after: 2000
  visualize_every: 1000
  max_steps: 300_000
  save_every: 500

  resume_path:
  ema_load_path:

  segment_optim:
    _target_: heavyball.ForeachAdamW
    _partial_: true
    lr: 6.0e-4
    weight_decay: 1.0e-4
    eps: 1e-10
    betas: ${tuple:[0.9, 0.99]} #[0.5, 0.9], gan training beta1 is zero
    caution: true
    foreach: true

  segment_sched:
    _target_: transformers.optimization.get_cosine_schedule_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 3

  log:
    run_comment: OSCD_dinov3_adaptor_wrapper
    log_with_time: True
    log_every: 10
  debug: true

val:
  val_duration: 1000
  max_val_iters: -1
