hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  # tokenizer ==========
  - dataset: OSCD
  - tokenizer: cosmos_f8c16p1_lora
  - accelerator: base
  - segment_model: dinov3_adaptor
  # self ===============
  - _self_

  # hydra overrides ====
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

ema:
  _target_: ema_pytorch.EMA
  _partial_: true
  beta: 0.999
  update_after_step: 1000
  update_every: 1
  allow_different_devices: true
  lazy_init_ema: true

segment_loss:
  _target_: src.stage2.segmentation.loss.seg_loss.HyperSegmentationLoss
  ignore_index: 255
  ce_weight: [1.0, 10.0]
  loss_weights: [0.5, 1.0, 0.5]

metric:
  _target_: src.stage2.segmentation.metrics.basic.HyperSegmentationScore
  n_classes: ${dataset.consts.num_classes}
  ignore_index: 255
  include_bg: false

train:
  tokenizer_name: cosmos_f8c16p1
  is_lora_mixin: true
  tokenizer_not_req_grad: true
  base_model_pretrained_path: # tokenizer base model loading
  peft_pretrained_path: # tokenizer peft model loading
  seperate_enc_dec: false
  online_tokenize: true
  quantizer_type:
  prepare_tokenizer_in_accelerator: false # aviod return base model of lora wrapper
  to_neg_1_1: true
  model_act_checkpoint: false
  val_slide_window: true
  grad_check: false

  use_single_img_indexing: false
  patches_per_image:
  macro_batch_size: 32

  proj_dir: runs/stage2_CD/
  finetune_strategy: finetune_all
  max_grad_norm: 0.03

  track_metrics_duration: -1
  track_metrics_after: 2000
  visualize_every: 1000
  max_steps: 300_000
  save_every: 500

  resume_path:
  ema_load_path:

  segment_optim:
    _target_: heavyball.ForeachAdamW
    _partial_: true
    lr: 4.0e-4
    weight_decay: 1.0e-4
    eps: 1e-10
    betas: ${tuple:[0.9, 0.99]} #[0.5, 0.9], gan training beta1 is zero
    caution: true
    foreach: true

  segment_sched:
    _target_: transformers.optimization.get_cosine_schedule_with_warmup
    _partial_: true
    num_warmup_steps: 100
    num_training_steps: ${train.max_steps}
    num_cycles: 1

  log:
    run_comment: OSCD_dinov3_adaptor
    log_with_time: True
    log_every: 10
  debug: true

val:
  val_duration: 500
  max_val_iters: -1
