hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - dataset: levir_cd
  - accelerator: base
  - segment_model: tokenizer_hybrid_bit_sdpa
  - _self_

  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

ema:
  _target_: ema_pytorch.EMA
  _partial_: true
  beta: 0.999
  update_after_step: 0
  update_every: 1

segment_loss:
  _target_: src.stage2.segmentation.loss.seg_loss.HyperSegmentationLoss
  ignore_index: 255
  ce_weight: null
  loss_weights: [0.5, 1.0, 0.3]
  mode: multiclass

metric:
  _target_: src.stage2.change_detection.metrics.basic.ChangeDetectionScore
  n_classes: ${dataset.consts.num_classes}
  ignore_index: null
  include_bg: true
  input_format: index

train:
  val_slide_window: false
  grad_check: false
  act_checkpoint: true
  val_slide_window_kwargs:
    patch_size: 128
    stride: 64

  use_single_img_indexing: false
  patches_per_image:
  macro_batch_size: 32

  proj_dir: runs/stage2_CD_wrapper/
  finetune_strategy: finetune_all
  max_grad_norm: 1.0

  track_metrics_duration: -1
  track_metrics_after: 2000
  visualize_every: 1000
  max_steps: 300_000
  save_every: 500
  is_neg_1_1: true

  resume_path:
  ema_load_path:

  segment_optim:
    _target_: src.utilities.optim.MuonFSDP.create_muon_optimizer
    _partial_: true
    betas: [0.95, 0.99]
    oned_param_algo: lion
    use_triton: true
    muon_params_defaults:
      lr: 3e-4
      weight_decay: 0.01
    oned_params_defaults:
      lr: 3e-4
      weight_decay: 0.0

  segment_sched:
    _target_: transformers.optimization.get_cosine_schedule_with_warmup
    _partial_: true
    num_warmup_steps: 0
    num_training_steps: ${train.max_steps}
    num_cycles: 2

  log:
    run_comment: ${dataset.dataset_name}_tokenizer_hybrid_bit_sdpa
    log_with_time: true
    log_every: 10
  debug: true

val:
  val_duration: 500
  max_val_iters: -1
