_target_: src.stage1.cosmos.cosmos_tokenizer.ContinuousImageTokenizer
attn_resolutions: [32]
channels: 128
channels_mult: [2, 4, 4]
dropout: 0.0
in_channels: ${dataset.consts.bands}
spatial_compression: 8
num_res_blocks: 2
out_channels: ${dataset.consts.bands}
resolution: 1024
patch_size: 4
patch_method: haar
latent_channels: 16
z_channels: 16
z_factor: 1
name: CI
formulation: AE
encoder: Default
decoder: Default
act_checkpoint: true
norm_in_quant_conv: false
uni_path: runs/stage1_cosmos/2025-05-29_16-24-09_cosmos_f8c16p4_uni/ema/tokenizer/model.safetensors
loading_type: pretrained
wrap_fsdp_last_layer: false
quantizer_type: null
hook_for_repa: false
padding_mode: reflect
block_name: res_block
attn_type: none
## downsample and upsample
downsample_type: ConvPixelUnshuffle
downsample_shortcut: averaging
upsample_type: ConvPixelShuffle
upsample_shortcut: duplicating
