hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  # tokenizer
  - tokenizer: no_diff_slots_base_t512_d16
  - dataset: hyperspectral
  - vq_loss: remote_clip_RN50
  - _self_
  # hydra overrides
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

accelerator:
  _target_: accelerate.Accelerator
  mixed_precision: bf16
  log_with: tensorboard
  dataloader_config:
    _target_: accelerate.utils.DataLoaderConfiguration
    split_batches: False
    even_batches: False
    non_blocking: True
    dispatch_batches: None
    use_seedable_sampler: False
    use_stateful_dataloader: False
  project_config:
    _target_: accelerate.utils.ProjectConfiguration
    # ==================
    # placeholder, changed by code
    project_dir: runs/stage1_1dtokenizer/
    logging_dir: runs/stage1_1dtokenizer/tensorboard
    # ==================
    total_limit: 5
    automatic_checkpoint_naming: true
  gradient_accumulation_plugin:
    _target_: accelerate.utils.GradientAccumulationPlugin
    num_steps: 2
    adjust_scheduler: false
    sync_with_dataloader: false
    sync_each_batch: false

dataset:
  used: DCF_2019
  dataset_names_to_bs:
    MMSeg_YREB: 28
    DCF_2019: 12
  transform_prob: 0.5

# not used if there is no quantizer
loss:
  repa_loss_weight: 0 # not used
  quantizer_loss_weight: 0.1

ema:
  beta: 0.99
  update_after_step: 100
  update_every: 2

train:
  proj_dir: runs/stage1_1d_tok/
  finetune_strategy: finetune_all
  max_grad_norm: 0.03
  track_metrics_duration: -1
  track_metrics_after: 2000
  visualize_every: 200
  max_steps: 200_000
  save_every: 1000
  use_disc: true
  use_lpips: false
  resume_path:
  ema_load_path:

  quantizer_type: ${tokenizer.quantizer_type}
  quantizer_kwargs: null

  tokenizer_optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 1.0e-4
    eps: 1.0e-8
    foreach: true

  disc_optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 1.0e-4
    eps: 1.0e-8
    foreach: true

  tokenizer_sched:
    _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 1
    reduced_factor: 2

  disc_sched:
    _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 1
    reduced_factor: 2

  log:
    run_comment: 1d_tok_no_diff_t512_d16
    log_with_time: true
    visualize_every: 200
    log_every: 10

  debug: true

val:
  sample_cfg: 1.0
  sample_use_ema: false
  val_duration: 1000
  max_val_iters: 4 # val only `max_val_iters` batches
