used: WV3
shuffle_size: -1
num_workers: 3
prefetch_factor: 6
shuffle_within_workers: false

dataset_names_to_bs:
  MMSeg_YREB: 32
  DCF_2019: 32
  DFC_2020: 32
  GID_GF2: 32
  DryadHyper: 32
  MUSLI: 32
  Houston: 7
  WV3: 32

dataset_names_to_n_channels:
  MMSeg_YREB: 12
  DCF_2019: 8
  DFC_2020: 13
  GID_GF2: 4
  DryadHyper: 224
  MUSLI: 438
  Houston: 50
  WV3: 8
  OHS: 32

dataset_names_to_rgb_channels:
  MMSeg_YREB: [4, 3, 2]
  DCF_2019: [4, 2, 0]
  DCF_2020: [9, 6, 3]
  GID_GF2: [4, 2, 0]
  DryadHyper: [90, 60, 40]
  Houston: [40, 20, 10]
  DFC_2020: [9, 6, 4]
  MUSLI: [66, 38, 16]
  WV3: [4, 2, 0]
  OHS: [18, 11, 6]

dataset_names_to_img_size:
  MMSeg_YREB: 256
  DCF_2019: 512
  DCF_2020: 256
  GID_GF2: 512
  DryadHyper: 128
  DFC_2020: 256
  Houston: 512
  MUSLI: 512
  WV3: 512
  OHS: 512

MMSeg_YREB_train:
  - - data/MMSeg_YREB/hyper_images/MMSeg_YREB_train_part-12_bands-MSI-{0000..0003}.tar

MMSeg_YREB_val:
  - - data/MMSeg_YREB/hyper_images/MMSeg_YREB_train_part-12_bands-MSI-0003.tar

DCF_2019_train:
  - - data/DCF_2019/hyper_images/DCF_2019_Track_2-8_bands-px_512-MSI-{0000..0017}.tar

DFC_2020_train:
  - - data/DCF_2020/hyper_images/DFC_2020_public-13_bands-px_256-MSI-{0000..0002}.tar

Houston_train:
  - - data/Houston-50_bands-px_512-MSI-0000.tar

Houston_val:
  - - data/Houston-50_bands-px_512-MSI-0000.tar

DryadHyper_train:
  - - data/DryadHyper/hyper_images/DryadHyper-224_bands-px_128-MSI-{0000..0002}.tar

GID_GF2_train:
  - - data/GID-GF2/hyper_images/GID-GF2-train-4_bands-px_512-MSI-{0000..0003}.tar
    - data/GID-GF2/hyper_images/GID-GF2-val-4_bands-px_512-MSI-{0000..0001}.tar

MUSLI_train:
  - - data/hyper_images/MUSLI_safetensors/safetensors

WV3_train:
  - - data/WorldView3/hyper_images/WorldView3-8_bands-px_256-MSI-0000.tar
  - - data/WorldView3/hyper_images/WorldView3-PAN-1_bands-px_512-MSI-0000.tar

WV3_val:
  - - data/WorldView3/hyper_images/WorldView3-8_bands-px_256-MSI-0000.tar
  - - data/WorldView3/hyper_images/WorldView3-PAN-1_bands-px_512-MSI-0000.tar

DFC_2020_val:
  - - data/DCF_2020/hyper_images/DFC_2020_public-13_bands-px_256-MSI-0002.tar

MUSLI_val:
  - - data/hyper_images/MUSLI_safetensors/safetensors

DryadHyper_val:
  - - data/DryadHyper/hyper_images/DryadHyper-224_bands-px_128-MSI-0002.tar

GID_GF2_val:
  - - data/GID-GF2/hyper_images/GID-GF2-val-4_bands-px_512-MSI-0000.tar

DCF_2019_val:
  - - data/DCF_2019/hyper_images/DCF_2019_Track_2-8_bands-px_512-MSI-{0015..0017}.tar

OHS_train:
  - - data/OHS/hyper_images/OHS-32_bands-px_512-MSI-{0000..0015}.tar

OHS_val:
  - - data/OHS/hyper_images/OHS-32_bands-px_512-MSI-{0013..0015}.tar

train_name: ${dataset.used}_train
val_name: ${dataset.used}_val
wds_path_train: ${dataset[${dataset.train_name}]}
wds_path_val: ${dataset[${dataset.val_name}]}
channels: ${dataset.dataset_names_to_n_channels[${dataset.used}]}
batch_size_train: ${dataset.dataset_names_to_bs[${dataset.used}]}
batch_size_val: 8
rgb_channels: ${dataset.dataset_names_to_rgb_channels[${dataset.used}]}
img_size: ${dataset.dataset_names_to_img_size[${dataset.used}]}
hyper_transforms_lst:
  - grayscale
  - rotation
  - cutmix
  - horizontal_flip
  - vertical_flip
transform_prob: 0.5
random_apply: [1, 2]
loader_type: webdataset
to_neg_1_1: true

# function entry
train_loader:
  _target_: src.data.hyperspectral_loader.get_hyperspectral_img_loaders_with_different_backends
  paths: ${dataset.wds_path_train}
  loader_type: ${dataset.loader_type}
  basic_kwargs:
    batch_size: ${dataset.batch_size_train}
    num_workers: ${dataset.num_workers}
    prefetch_factor: ${dataset.prefetch_factor}
    shuffle_within_workers: ${dataset.shuffle_within_workers}
    resample: true
    # check_channels: true
    # channels: 8

  # for the lora training wv3, gf2, qb, IKONOS
  # changed_kwargs_by_loader:
  #   - batch_size: 12
  #   - batch_size: 4
  #     channels: 8
  #     check_channels: true

val_loader:
  _target_: src.data.hyperspectral_loader.get_hyperspectral_img_loaders_with_different_backends
  paths: ${dataset.wds_path_val}
  basic_kwargs:
    batch_size: ${dataset.batch_size_val}
    num_workers: 0 #${dataset.num_workers}
    prefetch_factor: null #${dataset.prefetch_factor}
    shuffle_within_workers: false #${dataset.shuffle_within_workers}
    resample: true
  # changed_kwargs_by_loader:
  #   - batch_size: 4
  #   - batch_size: 4
  #     channels: 8
  #     check_channels: true
