used: MMSeg_YREB
shuffle_size: 100
num_workers: 3

dataset_names_to_bs:
  MMSeg_YREB: 32
  DCF_2019: 32

dataset_names_to_n_channels:
  MMSeg_YREB: 12
  DCF_2019: 8

dataset_names_to_rgb_channels:
  MMSeg_YREB: [4, 3, 2]
  DCF_2019: [4, 2, 0]

dataset_names_to_img_size:
  MMSeg_YREB: 256
  DCF_2019: 512

MMSeg_YREB_train:
  - data/MMSeg_YREB_train_part-12_bands-MSI-0000.tar
  - data/MMSeg_YREB_train_part-12_bands-MSI-0001.tar
  - data/MMSeg_YREB_train_part-12_bands-MSI-0002.tar

MMSeg_YREB_val:
  - data/MMSeg_YREB_train_part-12_bands-MSI-0003.tar

DCF_2019_train:
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0000.tar
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0001.tar
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0002.tar
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0003.tar
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0004.tar
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0005.tar
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0006.tar
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0007.tar
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0008.tar
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0009.tar
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0010.tar
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0011.tar
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0012.tar
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0013.tar
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0014.tar
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0015.tar
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0016.tar

DCF_2019_val:
  - data/DCF_2019_Track_2-8_bands-px_512-MSI-0017.tar

train_name: ${dataset.used}_train
val_name: ${dataset.used}_val
wds_path_train: ${dataset[${dataset.train_name}]}
wds_path_val: ${dataset[${dataset.val_name}]}
channels: ${dataset.dataset_names_to_n_channels[${dataset.used}]}
batch_size_train: ${dataset.dataset_names_to_bs[${dataset.used}]}
batch_size_val: 4
rgb_channels: ${dataset.dataset_names_to_rgb_channels[${dataset.used}]}
img_size: ${dataset.dataset_names_to_img_size[${dataset.used}]}
hyper_transforms_lst:
  - grayscale
  - rotation
  - cutmix
  - horizontal_flip
  - vertical_flip
transform_prob: 0.5
random_apply: [1, 2]
