train_bs: 3
val_bs: 1

data_type: label_centrical
label_mode: seg
patch_size: 128
micro_batch_size: 12

consts:
  dataset_name: OSCD
  num_classes: 2
  bands: 13
  unchanged_label: 0
  changed_label: 1

train:
  _target_: src.stage2.change_detection.data.oscd_loader.create_oscd_loader
  wds_paths:
    - data/Downstreams/ChangeDetection/OSCD/OSCD_13bands_train.npy.tar
    - data/Downstreams/ChangeDetection/OSCD/OSCD_13bands_test.npy.tar
  batch_size: ${dataset.train_bs}
  to_neg_1_1: false
  num_workers: 4
  shared_norm: true
  resample: true
  shuffle: true
  shuffle_size: 20
  pin_memory: true
  prefetch_factor: 6
  random_flip_prob: 0.8
  crop_size: 256

val:
  _target_: src.stage2.change_detection.data.oscd_loader.create_oscd_loader
  wds_paths:
    - data/Downstreams/ChangeDetection/OSCD/OSCD_13bands_test.npy.tar
  batch_size: ${dataset.val_bs}
  to_neg_1_1: false
  num_workers: 2
  shared_norm: true
  resample: false
  shuffle: true
  shuffle_size: 20
  pin_memory: true
