_target_: src.stage2.utilities.amotized.amotized_model_wrapper.AmotizedModelMixin
_partial_: true # for decode_fn

# Model configuration
amotize_type: "latent_to_pixel_fusion"
backward_decoder: true
learn_decoder: false

# Amotized model (Transformer branch)
amotized_model:
  _target_: src.stage2.pansharpening.models.transformer.Transformer
  cfg:
    _target_: src.stage2.pansharpening.models.transformer.TransformerConfig
    in_dim: 16
    dim: 384
    depth: 8
    num_heads: 8
    mlp_ratio: 4.0
    drop: 0.0
    drop_path: 0.0
    patch_size: 1
    out_channels: 256
    norm_layer: "rmsnorm"
    mlp_norm_layer: "rmsnorm"
    act_layer: "silu"
    pos_embed_type: "sincos"
    input_size: 32
    with_raw_img: false
    raw_img_size: null
    raw_img_chans: null
    feature_layer_ids: null

# Pixel model (NAFDecoder branch)
pixel_model:
  _target_: src.stage2.pansharpening.models.naf.PansharpeningNAFDecoderNet
  cfg:
    _target_: src.stage2.pansharpening.models.naf.PansharpeningNAFDecoderNetConfig
    pan_channel: 1
    ms_channel: ${dataset.consts.bands}
    width: 384
    middle_blk_num: 2
    dec_blk_nums: [2, 1, 1]
    condition_channel: 256
    residual_type: pan
    dw_expand: 2
    ffn_expand: 2
    patch_size: 1
    block_drop: 0.0
    output_rescale: true
    is_neg_1_1: true
    up_ratio: 4
    decoder_cross_attn_idx: [0, 1]
    cross_attn_kwargs:
      n_q_heads: 4
      n_kv_heads: 4
      cross_attn_patch_size: 2
