_target_: src.stage2.layers.wrapper.tokenizer_wrapper.DownstreamModelTokenizerWrapper

# Tokenizer configuration (from cosmos_f8c16p1_lora.yaml)
tokenizer:
  _target_: src.stage1.cosmos.lora_mixin.TokenizerLoRAMixin
  tokenizer:
    _target_: src.stage1.cosmos.cosmos_tokenizer.ContinuousImageTokenizer.create_model
    model:
      attn_resolutions: [32]
      channels: 128
      channels_mult: [2, 4, 4]
      dropout: 0.0
      in_channels: ${list:[3, 4, 8, 10, 12, 13, 32, 50, 150, 175, 202, 224, 242, 368, 369]}
      spatial_compression: 8
      num_res_blocks: 2
      out_channels: ${list:[3, 4, 8, 10, 12, 13, 32, 50, 150, 175, 202, 224, 242, 368, 369]}
      resolution: 1024
      z_channels: 16
      act_checkpoint: false
      latent_channels: 16
      norm_type: gn
      norm_groups: 32
      block_name: res_block
      moe_token_mixer_type: res_block
      hidden_factor: 4
      use_residual_factor: false
      # others
      patch_method: haar
      patch_size: 1
      attn_type: none
      padding_mode: reflect # for boundary?
    # repa
    use_repa_loss: false
    use_vf_loss: false
    hook_module: decoder.decoder.mid.block_2
    vf_on_z_or_module: z # [z, module]
    dino_feature_dim: 1024
    # loading
    enc_path: ""
    dec_path: ""
    uni_path: runs/stage1_cosmos/2025-09-13_17-16-19_cosmos_f8c16p1_unified_hyperspectral_latent_noise=0.0_channel_drop=False/ema/tokenizer/model.safetensors
    loading_type: pretrained
    # quant
    norm_in_quant_conv: false
  lora_weights:
    WV3: runs/stage1_cosmos_lora/2025-09-14_23-31-37_cosmos_lora=lora_r=32_f8c16p1_WV3/peft_ckpt/WV3/adapter_model.safetensors
    QB: runs/stage1_cosmos_lora/2025-09-14_23-27-18_cosmos_lora=lora_r=32_f8c16p1_QB/peft_ckpt/QB/adapter_model.safetensors
  lora_hyper_chans:
    WV3: 8
    QB: 4
  active_lora: ${dataset.cfgs.used}

# Pansharpening model configuration (from nafnet.yaml)
downstream_model:
  _target_: src.stage2.utilities.amotized.amotized_model_wrapper.AmotizedModelMixin
  _partial_: true # for decode_fn

  # Model configuration
  amotize_type: "latent_to_pixel_fusion"
  backward_decoder: false
  learn_decoder: false

  # Amotized model (Transformer branch)
  amotized_model:
    _target_: src.stage2.layers.naflex.NaFlexVitAdpoted
    cfg:
      _target_: src.stage2.layers.naflex.NaFlexVitCfg
      embed_dim: 256
      patch_size: 1
      depth: 8
      num_heads: 8
      mlp_ratio: 4.0
      qk_norm: true
      pos_embed: learned
      global_pool: ""
      norm_layer: rmsnorm
      attn_type: eva
    cfg2:
      _target_: src.stage2.layers.naflex.NaFlexVitCfgAdpoted
      img_size: 32
      in_chans: 16
      out_chans: 256
      patch_size: 1

  # Pixel model (NAFNet branch)
  pixel_model:
    _target_: src.stage2.pansharpening.models.naf.PansharpeningNAFNet
    cfg:
      _target_: src.stage2.pansharpening.models.naf.PansharpeningNAFNetConfig
      pan_channel: 1
      ms_channel: ${dataset.consts.bands}
      width: 64
      middle_blk_num: 1
      enc_blk_nums: [1, 1, 1]
      dec_blk_nums: [1, 1, 1]
      condition_channel: 256 # comes from the de-tokenizer
      patch_size: 1
      dw_expand: 1
      ffn_expand: 2
      condition_on_decoder: true
      residual_type: ms
      is_neg_1_1: true
      output_rescale: true

# Wrapper configuration
froze_tokenizer: true
n_img_encoded: 3 # For pansharpening, we have 3 images: LRMS, PAN, and HRMS
tokenizer_scale_shift: [6.25221633, 0.0] # std, mean from cosmos_f8c16p1_lora.yaml
