consts:
  bands: 191

train_loader:
  _target_: src.data.hyperspectral_loader.get_hyperspectral_img_loaders_with_different_backends
  paths: data/Downstreams/WDCDenoise/hyper_images/Washington_DC_mall-191_bands-px_192-0000.tar
  loader_type: "wds"
  basic_kwargs:
    batch_size: 6
    num_workers: 1
    prefetch_factor: 2
    shuffle_within_workers: false
    resample: true
    check_channels_n: ${dataset.dataset_channel}
    quantile_img_clip: 1.0
    per_channel_norm: false
    random_one_key: false
    resize_before_transform: 192
    # keys_to_remove: ["endmembers", "abunds", "init_vca_indices"]

val_loader:
