_target_: src.stage1.cosmos.two_dim_diffusion_slots.TwoDimDiffusionSlots
tokenizer_cfg:
  attn_resolutions: [32]
  channels: 128
  channels_mult: [2, 4, 4]
  dropout: 0.0
  in_channels: ${dataset.channels}
  spatial_compression: 16
  num_res_blocks: 2
  out_channels: 12
  resolution: ${dataset.dataset_names_to_img_size[${dataset.used}]}
  patch_size: 4
  decoder_patch_size: 4
  patch_method: "rearrange"
  latent_channels: 16
  z_channels: 16
  z_factor: 1
  name: "CIDiff"
  formulation: "AE"
  encoder: "Default"
  decoder: "Diffusion"
  diff_cond_inject_strategy: "inject_full"
  time_scale: 1000.0
  z_cfg_drop: 0.2
  act_checkpoint: false
  use_residual_factor: false
enc_path: null
dec_path: null
use_repa: false
img_channels: ${dataset.channels}
enc_img_size: ${dataset.dataset_names_to_img_size[${dataset.used}]}
diffusion_type: fm
num_sampling_steps: ddim25
fm_sample_type: ode
fm_options:
  path_type: Linear
  prediction: x1
  train_eps: 1.0e-4
  sample_eps: 1.0e-4
compile_model: false
quantizer_type:
quantizer_kwargs:
