_target_: src.stage1.cosmos.cosmos_mingtok.FlowTokenizer.create_model
flow_type: fm
decoder_type: uvit

cfg:
  low_level_encoder:
    in_chan: 512
    embed_dim: 768
    z_dim: 768
    latent_dim: 32
    depth: 12
    num_heads: 12
    patch_size: 16
    out_patch_size: 1
    patcher_type: patch_embedder
    # patch_prog_dims: [386, 386, 512]
    additional_pe: true
    pe_type: rope

  semantic_decoder:
    in_chan: 32
    out_chan: 1024
    embed_dim: 1024
    depth: 12
    num_heads: 16
    patch_size: 1
    additional_pe: false
    pe_type: rope

  pixel_decoder:
    in_chan: 512
    z_dim: 1024
    num_attention_heads: 8
    mid_nlayers: 12
    act_fn: gelu
    vit_act_fn: silu
    ch_mult: [1, 1, 2, 4, 8]
    mid_theta: 10000.0 # rope theta
    jvp: false

    flow_type: fm
    time_cond_type: t
    cfg_prob: 0.0
    transport: # fm transport
      model_type: velocity
      path_type: linear
      loss_type: velocity
      train_eps: 0.
      sample_eps: 0.
      time_sample_type: sigmoid

  tokenizer:
    decoder_type: uvit
    sampling_options_default:
      sampling_method: euler
      num_steps: 8 # 100 for fm only, 10 for add discriminator
      cfg: 1.0
      progress: true
      cfg_interval: [0.0, 0.7]

  repa_proj:
    low_lvl_repa_out_chan: 1024
    sem_repa_out_chan: 1024
