tokenizer:
  _target_: src.stage1.one_d_tokenizer.semanticist.diffuse_slot.DiffuseSlot
  encoder: vit_base_patch16
  drop_path_rate: 0.1
  img_channels: 8
  enc_img_size: 256
  enc_causal: True
  num_slots: 512
  slot_dim: 16
  norm_slots: False
  enable_nest: True
  enable_nest_after: 2000 # after n_iters enable nest latent sampler
  vae: null # no use pretrained vae
  dit_model: DiT-B-4
  diffusion_type: diffusion
  num_sampling_steps: ddim25
  use_repa: False
  repa_encoder_depth: 8
  repa_loss_weight: 1.0
  dit_in_channels: 16
  encoder_block_checkpoint: true
  decoder_block_checkpoint: true
  compile_model: true
  learn_sigma: true
  fm_sample_type: null # not used for diffusion
