hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - _self_
  # tokenizer
  - tokenizer: cosmos_base
  - dataset: hyperspectral
  # hydra overrides
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

accelerator:
  _target_: accelerate.Accelerator
  mixed_precision: bf16
  log_with: tensorboard
  dataloader_config:
    _target_: accelerate.utils.DataLoaderConfiguration
    split_batches: False
    even_batches: False
    non_blocking: True
    dispatch_batches: None
    use_seedable_sampler: False
    use_stateful_dataloader: False
  project_config:
    _target_: accelerate.utils.ProjectConfiguration
    # ==================
    # placeholder, changed by code
    project_dir: runs/stage1_1dtokenizer/
    logging_dir: runs/stage1_1dtokenizer/tensorboard
    # ==================
    total_limit: 5
    automatic_checkpoint_naming: true
  gradient_accumulation_plugin:
    _target_: accelerate.utils.GradientAccumulationPlugin
    num_steps: 2
    adjust_scheduler: false
    sync_with_dataloader: false
    sync_each_batch: false

loss:
  repa_loss_weight: 0.1 # not used
  quantizer_loss_weight: 1.0

vq_loss:
  _target_: src.stage1.cosmos.losses.gan_loss.loss.VQLPIPSWithDiscriminator
  disc_ndf: 64
  perceptual_weight: 0.0 # do not support for hyperspectral images
  loss_ssim: true
  use_actnorm: false
  disc_in_channels: ${dataset.channels}
  lecam_loss_weight: 0.05
  disc_weight: 0.1
  gen_loss_weight:

ema:
  beta: 0.999
  update_after_step: 100
  update_every: 2

train:
  proj_dir: runs/stage1_cosmos_diffusive/
  finetune_strategy: finetune_all
  max_grad_norm: 0.03
  track_metrics_duration: -1
  track_metrics_after: 2000
  visualize_every: 200
  max_steps: 200_000
  save_every: 1000
  use_disc: true

  tokenizer_optimizer:
    _target_: src.utilities.optim.mars.MARS
    _partial_: true
    lr: 3.0e-4
    weight_decay: 1.0e-6
    betas: [0.9, 0.95]

  disc_optimizer:
    _target_: src.utilities.optim.mars.MARS
    _partial_: true
    lr: 3.0e-4
    weight_decay: 1.0e-6
    betas: [0.9, 0.95]

  tokenizer_sched:
    _target_: transformers.optimization.get_cosine_schedule_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 2

  disc_sched:
    _target_: transformers.optimization.get_cosine_schedule_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 2

  log:
    run_comment: 1d_tokenizer_train
    log_with_time: true
    visualize_every: 200
    log_every: 10

  debug: false

val:
  sample_cfg: 2.0
  val_duration: 1000
  max_val_iters: 4 # val only `max_val_iters` batches
