hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - _self_
  # tokenizer
  - tokenizer: cosmos_base
  - dataset: hyperspectral
  # hydra overrides
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

accelerator:
  _target_: accelerate.Accelerator
  mixed_precision: bf16
  log_with: tensorboard
  dataloader_config:
    _target_: accelerate.utils.DataLoaderConfiguration
    split_batches: False
    even_batches: False
    non_blocking: True
    dispatch_batches: None
    use_seedable_sampler: False
    use_stateful_dataloader: False
  project_config:
    _target_: accelerate.utils.ProjectConfiguration
    # ==================
    # placeholder, changed by code
    project_dir: runs/stage1_1dtokenizer/
    logging_dir: runs/stage1_1dtokenizer/tensorboard
    # ==================
    total_limit: 5
    automatic_checkpoint_naming: true
  gradient_accumulation_plugin:
    _target_: accelerate.utils.GradientAccumulationPlugin
    num_steps: 2
    adjust_scheduler: false
    sync_with_dataloader: false
    sync_each_batch: false

loss:
  repa_loss_weight: 0.1 # not used
  quantizer_loss_weight: 1.0

vq_loss:
  _target_: src.stage1.utilities.VQLPIPSWithDiscriminator
  disc_network_type: patchgan
  disc_ndf: 64
  use_actnorm: false
  disc_input_size: ${dataset.img_size}
  disc_in_channels: ${dataset.channels}
  # perceptual
  perceptual_weight: 0.1
  perceptual_type: resnet
  perceptual_groups_to_select: 0.5
  perceptual_loss_on_logits: false
  gram_model: null
  gram_loss_weight: 1.0
  # ssim loss
  loss_ssim: true
  ssim_weight: 0.1
  # lecam
  lecam_loss_weight: 0.001
  # recon loss
  reconstruction_weight: 4.0
  force_not_use_recon_loss: false # compute the reconstruction loss outside
  # gen and disc losses
  gen_loss_weight: null
  disc_weight: 0.1
  disc_start: 0
  disc_reg_r1: 10
  disc_reg_freq: 0 # 0 means disabled
  disc_loss: non_saturate
  # quantizer
  quantizer_type: null
  quantizer_options:
    quantizer_loss_weight: 0.1
    codebook_enlarge_ratio: 3.0
    codebook_enlarge_steps: 2000

ema:
  beta: 0.999
  update_after_step: 100
  update_every: 2

train:
  proj_dir: runs/stage1_cosmos_diffusive/
  finetune_strategy: finetune_all
  max_grad_norm: 0.03
  track_metrics_duration: -1
  track_metrics_after: 2000
  visualize_every: 200
  max_steps: 200_000
  save_every: 1000
  use_disc: true
  resume_path:
  ema_load_path:

  tokenizer_optimizer:
    _target_: src.utilities.optim.mars.MARS
    _partial_: true
    lr: 3.0e-4
    weight_decay: 1.0e-4

  disc_optimizer:
    _target_: src.utilities.optim.mars.MARS
    _partial_: true
    lr: 3.0e-4
    weight_decay: 1.0e-4

  tokenizer_sched:
    _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 4
    reduced_factor: 2

  disc_sched:
    _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 4
    reduced_factor: 2
  log:
    run_comment: 1d_tokenizer_train
    log_with_time: true
    visualize_every: 200
    log_every: 10

  debug: false

val:
  sample_use_ema: true
  sample_cfg: 2.0
  val_duration: 1000
  max_val_iters: 4 # val only `max_val_iters` batches
