_target_: accelerate.Accelerator
mixed_precision: bf16
log_with: tensorboard
dataloader_config:
  _target_: accelerate.utils.DataLoaderConfiguration
  split_batches: false
  even_batches: false
  non_blocking: true
  dispatch_batches: null
  use_seedable_sampler: false
  use_stateful_dataloader: false
project_config:
  _target_: accelerate.utils.ProjectConfiguration
  # placeholder, will be updated by trainer
  project_dir: runs/stage2_cloud_removal/
  logging_dir: runs/stage2_cloud_removal/tensorboard
  total_limit: 2
  automatic_checkpoint_naming: true
gradient_accumulation_plugin:
  _target_: accelerate.utils.GradientAccumulationPlugin
  num_steps: 1
  adjust_scheduler: false
  sync_with_dataloader: false
  sync_each_batch: false
