_target_: src.stage2.cloud_removal.diffusion.vae.CosmosRSVAE
# model_path: runs/stage1_cosmos_nested/2025-12-21_02-01-17_cosmos_f8c16p1_litdata_one_loader_irepa-spatial-norm_noisy_latent_aug/ema/tokenizer/model.safetensors
model_path: runs/stage1_cosmos_nested/pretrained/2025-12-20-nested-no-lcr-iter_470k/tokenizer/model.safetensors
dtype: bf16
