hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  # wrapper ==========
  - dataset: pancollection_v1
  - accelerator: base
  - pansharp_model: pansharp_wrapper_nafnet_cosmos
  # self ===============
  - _self_
  # hydra overrides ====
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

accelerator:
  mixed_precision: "bf16"

dataset:
  cfgs:
    used: WV3
    batch_size_train: 16

ema:
  _target_: ema_pytorch.EMA
  _partial_: true
  beta: 0.995
  update_after_step: 1000
  update_every: 2
  use_foreach: true
  allow_different_devices: true
  move_ema_to_online_device: true

train:
  grad_check: false
  proj_dir: runs/stage2_pansharpening_wrapper/
  finetune_strategy: finetune_all
  max_grad_norm: 0.3

  track_metrics_duration: -1
  track_metrics_after: 1000
  visualize_every: 500
  max_steps: 100_000
  save_every: 1000

  to_neg_1_1: false
  pansp_ratio: 4
  online_tokenize: true
  add_pan_processor: false

  resume_path:
  ema_load_path: #runs/stage2_pansharpening_wrapper/2025-09-28_00-33-36_WV3_nat_2/ema

  pansharpening_loss:
    _target_: src.stage2.pansharpening.loss.amotized.AmotizedPixelLoss
    pixel_loss_type: l1ssim
    amotized_loss:
      _target_: torch.nn.L1Loss
    pixel_loss_kwargs:
      weighted_r: [1.0, 0.1] # l1ssim weights
    factors: [0.0, 1.0] # latent and pixel weights
    is_neg_1_1: false

  pansharp_optim:
    _target_: src.utilities.optim.MuonFSDP.create_muon_optimizer
    _partial_: true
    lr: 5.0e-4
    mu: 0.98
    betas: [0.99, 0.995]
    adjust_lr: rms_norm
    use_triton: true
    nesterov: true
    oned_param_algo: lion
    # muon_params_defaults:
    #   lr: 4.0e-4
    #   weight_decay: 0.1
    # oned_params_defaults:
    #   lr: 4.0e-4
    #   weight_decay: 0.0

    # _target_: heavyball.ForeachAdamW
    # _partial_: true
    # lr: 1e-3
    # weight_decay: 1.0e-4
    # betas: ${tuple:[0.95, 0.99]}
    # caution: true
    # mars: false
    # foreach: true
    # eps: 1.0e-9

    # _target_: torch.optim.AdamW
    # _partial_: true
    # lr: 6.0e-4
    # weight_decay: 1.0e-4
    # eps: 1.0e-9
    # betas: ${tuple:[0.95, 0.99]}
    # foreach: true

  pansharp_sched:
    _target_: transformers.optimization.get_cosine_schedule_with_warmup
    _partial_: true
    num_warmup_steps: 100
    num_training_steps: ${train.max_steps}
    num_cycles: 4

  log:
    run_comment: f8c16p1_${dataset.cfgs.used}_nafnet_wrapper
    log_with_time: true
    log_every: 10

  debug: true

val:
  val_duration: 500
  max_val_reduced_iters: -1 # val only `max_val_iters` batches
  max_val_full_iters: -1 # val_full only `max_val_iters` batches
  val_use_patches: true
  crop_batch_size: 64
