hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  # tokenizer ==========
  - dataset: pansharpening_data
  - tokenizer: cosmos_f8c16p1_lora
  - accelerator: base
  - pansharp_model: nafnet
  # self ===============
  - _self_

  # hydra overrides ====
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

dataset:
  cfgs:
    used: WV3

ema:
  _target_: ema_pytorch.EMA
  _partial_: true
  beta: 0.999
  update_after_step: 1000
  update_every: 2
  allow_different_devices: true

train:
  tokenizer_name: cosmos_f8c16p4
  is_lora_mixin: true
  tokenizer_not_req_grad: true
  base_model_pretrained_path: "" # tokenizer base model loading
  peft_pretrained_path: "" # tokenizer peft model loading
  seperate_enc_dec: false
  online_tokenize: true
  quantizer_type:
  prepare_tokenizer_in_accelerator: false # aviod return base model of lora wrapper
  to_neg_1_1: true
  model_act_checkpoint: true
  pansp_ratio: 4

  proj_dir: runs/stage2_pansharpening/
  finetune_strategy: finetune_all
  max_grad_norm: 0.03

  track_metrics_duration: -1
  track_metrics_after: 2000
  visualize_every: 200
  max_steps: 400_000
  save_every: 500

  resume_path:
  ema_load_path: #runs/stage1_cosmos/2025-04-11_03-19-56_cosmos_pretrained_f8c16p4_percep_remote_clip_RN50/ema

  pansharpening_loss:
    _target_: src.stage2.pansharpening.loss.amotized.AmotizedPixelLoss
    pixel_loss_type: l1ssim
    amotized_loss:
      _target_: torch.nn.MSELoss
    pixel_loss_kwargs:
      weighted_r: [1.0, 0.1]
    factors: [0.0, 1.0]

  pansharp_optim:
    # _target_: torch.optim.AdamW
    # _partial_: true
    # lr: 4.0e-4
    # eps: 1.0e-8
    # foreach: true
    _target_: src.utilities.optim.get_muon_optimizer
    _partial_: true
    lr: 6.0e-4
    weight_decay: 0.1
    adamw_eps: 1.0e-8
    ns_diff_abc: true
    ns_norm: false
    momentum: 0.9
    adamw_betas: ${tuple:[0.9, 0.95]} #[0.5, 0.9], gan training beta1 is zero
    adamw_wd: 0.
    # betas: [0.8, 0.95]

  pansharp_sched:
    _target_: transformers.optimization.get_cosine_schedule_with_warmup
    _partial_: true
    num_warmup_steps: 100
    num_training_steps: ${train.max_steps}
    num_cycles: 1

  log:
    run_comment: f8c16p1_${dataset.cfgs.used}_vitmain
    log_with_time: True
    visualize_every: 200
    log_every: 10

  debug: true

val:
  val_duration: 500
  max_val_iters: -1 # val only `max_val_iters` batches
