hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  # tokenizer ==========
  - dataset: unified_hyperspectral # [hyperspectral, unified_hyperspectral]
  - tokenizer: uni_cosmos_f8c16p1_nested # base tokenizer
  - quantizer: quant
  - accelerator: base
  - vq_loss: remote_clip_RN50
  # self ============
  - _self_

  # hydra overrides ====
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

accelerator:
  gradient_accumulation_plugin:
    num_steps: 1

vq_loss:
  # perceptual loss
  perceptual_weight: 0.05
  # repa loss
  repa_loss_weight: 0.02 # 0.1
  repa_loss_options:
    c_dim_first: true
    build_proj: false
    rgb_channels: mean
    img_resize: 512 # null for no resize
    repa_img_size: 512
    repa_model_name: "dinov3_vitl16"
    feature_resample_type: match_teacher
    loss_type: am_radio
    feature_normalize: true
  # vf loss
  vf_loss_weight:
  vf_loss_options:
    c_dim_first: true
    build_proj: false
    rgb_channels: mean #${dataset.rgb_channels}
    img_resize: 384
    repa_img_size: 384
    distmat_margin: 0.25
    cos_margin: 0.5
    repa_model_name: "dinov3_vitl16"
  # gram loss
  gram_loss_weight:
  gram_loss_options:
    c_dim_first: true
    build_proj: false
    rgb_channels: mean
    img_resize: 384 # null for no resize
    repa_img_size: 384
    repa_model_name: "dinov3_vitl16"
  # quantizer loss
  quantizer_type: bsq
  quantizer_options:
  # discriminator loss
  disc_network_type: patchgan # [patchgan, patchgan_v2, stylegan, r3gan]
  disc_ndf: 128
  disc_num_layers: 3
  use_actnorm: false
  disc_norm_type: bn2d #bn2d # gn or bn? works with patchgan_v2; bn does not support the r1, r2 loss
  disc_start_for_g: 0
  disc_start_for_d: 0
  disc_loss: relative
  ssim_weight: 0.06
  disc_weight: 0.1
  reconstruction_loss_type: mse
  # r1, r2 loss seems not necessary
  # disc_reg_gamma: 1
  # disc_reg_type: r1r2
  # disc_reg_freq: 2

tokenizer:
  # repa
  use_repa_loss: true
  use_vf_loss: false
  hook_module: decoder.decoder.mid.block_2
  vf_on_z_or_module: z # [z, module]
  dino_feature_dim: 1024

  # quantizer
  quantizer_type: bsq

  # loading
  uni_path:
  loading_type:

  # augmentations
  latent_noise_prob: 0.0
  use_channel_drop: false

  # blocks
  model:
    norm_type: gn
    norm_groups: 32
    block_name: res_block
    moe_token_mixer_type: res_block
    hidden_factor: 4
    use_residual_factor: false

    # others
    patch_method: haar
    patch_size: 1
    attn_type: none
    padding_mode: reflect # for boundary?
    adaptive_mode: interp

    # latents
    latent_channels: 64
    z_channels: 256 # [256, 16]

    # train
    act_checkpoint: true

  channel_drop_config:
    drop_type: ${list:[4, 8, 12]}
    max_channels: ${tokenizer.model.latent_channels}
    drop_prob: 0.5

ema:
  _target_: ema_pytorch.EMA
  _partial_: true
  beta: 0.999
  update_after_step: 1000
  update_every: 2
  use_foreach: true
  allow_different_devices: true
  update_model_with_ema_every: 5000

train:
  tokenizer_name: cosmos_bsq
  proj_dir: runs/stage1_cosmos_bsq/
  finetune_strategy: finetune_all
  max_grad_norm: 1.0
  track_metrics: true
  track_metrics_duration: -1
  track_metrics_after: 0
  visualize_every: 500
  max_steps: 1_000_000
  save_every: 1_000
  grad_checkpoint: true
  seperate_enc_dec: false
  only_load_tokenizer: false
  grad_check: false
  compile_model: false
  resume_path: #runs/stage1_cosmos_bsq/2025-11-16_21-18-55_nested_cosmos_f8c64p1_bsq_repa_unified_hyperspectral/checkpoints/checkpoint_48
  ema_load_path: runs/stage1_cosmos_bsq/2025-11-16_21-18-55_nested_cosmos_f8c64p1_bsq_repa_unified_hyperspectral/ema

  finetune_cfg:
    refine_decoder_head_n_layers: all
    adapt_latent_n_layers: 0

  tokenizer_optimizer:
    # _target_: src.utilities.optim.get_muon_optimizer
    # _partial_: true
    # lr: 3.0e-4
    # weight_decay: 0.1
    # adamw_eps: 1.0e-9
    # ns_diff_abc: true
    # ns_norm: false
    # momentum: 0.9
    # adamw_betas: ${tuple:[0.9, 0.95]} #[0.5, 0.9], gan training beta1 is zero
    # adamw_wd: 0.

    _target_: src.utilities.optim.MuonFSDP.create_muon_optimizer
    _partial_: true
    betas: ${tuple:[0.95, 0.99]}
    oned_param_algo: lion
    use_triton: false
    muon_params_defaults:
      lr: 4.0e-4
      weight_decay: 0.01
    oned_params_defaults:
      lr: 4.0e-4
      weight_decay: 0.0

    # _target_: heavyball.ForeachAdamW
    # _partial_: true
    # lr: 3.0e-4
    # weight_decay: 1.0e-4
    # eps: 1e-9
    # betas: ${tuple:[0.9, 0.999]} #[0.5, 0.9], gan training beta1 is zero
    # caution: true
    # foreach: true

    # weight_decay: 0.1
    # adamw_eps: 1.0e-8
    # ns_diff_abc: true
    # ns_norm: false
    # momentum: 0.9
    # adamw_betas: ${tuple:[0.9, 0.95]} #[0.5, 0.9], gan training beta1 is zero
    # adamw_wd: 0.

  disc_optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 2.0e-4
    betas: ${tuple:[0.5, 0.9]}
    weight_decay: 1.0e-6
    eps: 1.0e-8
    foreach: true

    # _target_: heavyball.ForeachAdamW
    # _partial_: true
    # lr: 3.0e-4
    # weight_decay: 1.0e-4
    # eps: 1e-9
    # betas: ${tuple:[0.9, 0.999]} #[0.5, 0.9], gan training beta1 is zero
    # caution: true
    # foreach: true

    # _target_: src.utilities.optim.get_muon_optimizer
    # _partial_: true
    # lr: 3.0e-4
    # weight_decay: 0.1
    # adamw_eps: 1.0e-9
    # ns_diff_abc: true
    # ns_norm: false
    # momentum: 0.9
    # adamw_betas: ${tuple:[0.9, 0.95]} #[0.5, 0.9], gan training beta1 is zero
    # adamw_wd: 0.

  tokenizer_sched:
    _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 1
    reduced_factor: 2
    min_lr: 1.0e-5

  disc_sched:
    _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 1
    reduced_factor: 2
    min_lr: 1.0e-5

  log:
    run_comment: nested_cosmos_f${tokenizer.model.spatial_compression}c${tokenizer.model.latent_channels}p1_bsq_repa_${dataset.used}
    log_with_time: true
    visualize_every: 500
    log_every: 10

  debug: true

val:
  val_duration: 1000
  max_val_iters: 200 # val only `max_val_iters` batches
