defaults:
  # tokenizer ==========
  - dataset: litdata_one_loader # [hyperspectral, unified_hyperspectral, litdata_one_loader]
  - tokenizer: uni_cosmos_f8c16p1_nested # base tokenizer
  - quantizer: quant
  - accelerator: base
  - vq_loss: remote_clip_RN50
  # self ============
  - _self_

  # hydra overrides ====
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  run:
    dir: runs/stage1_cosmos_bsq/${now:%Y-%m-%d}/${now:%H-%M-%S}_${train.log.run_comment}
  output_subdir: hydra_config

accelerator:
  gradient_accumulation_plugin:
    num_steps: 1

dataset:
  train_loader:
    macro_sampled_batch_size: { 128: 32, 256: 16, 512: 16 }
    loader_kwargs:
      num_workers: 12
      batch_size: 6
      prefetch_factor: 2
      persistent_workers: true
  val_loader:
    macro_sampled_batch_size: { 128: 8, 256: 8, 512: 8 }
    loader_kwargs:
      num_workers: 6
      batch_size: 4
      pin_memory: true
      drop_last: true
      persistent_workers: true

vq_loss:
  # perceptual loss
  perceptual_weight: 0.1
  # repa loss
  repa_loss_weight: 0 # 0.1
  repa_loss_options:
    c_dim_first: true
    build_proj: false
    rgb_channels: mean
    img_resize: 512 # null for no resize
    repa_img_size: 512
    repa_model_type: dinov3
    repa_model_name: "dinov3_vitl16"
    feature_resample_type: match_teacher
    loss_type: hier_distillation
    feature_normalize: spatial
    get_hier_teacher_feature: true
  # vf loss
  vf_loss_weight:
  vf_loss_options:
    c_dim_first: true
    build_proj: false
    rgb_channels: mean #${dataset.rgb_channels}
    img_resize: 384
    repa_img_size: 384
    distmat_margin: 0.25
    cos_margin: 0.5
    repa_model_name: "dinov3_vitl16"
  # gram loss
  gram_loss_weight:
  gram_loss_options:
    c_dim_first: true
    build_proj: false
    rgb_channels: mean
    img_resize: 384 # null for no resize
    repa_img_size: 384
    repa_model_name: "dinov3_vitl16"
  # quantizer loss
  quantizer_type: bsq
  quantizer_options:
    quantizer_loss_weight: 1.
  # discriminator loss
  disc_network_type: patchgan # [patchgan, patchgan_v2, stylegan, r3gan]
  disc_ndf: 128
  disc_num_layers: 3
  use_actnorm: false
  disc_norm_type: bn2d #bn2d # gn or bn? works with patchgan_v2; bn does not support the r1, r2 loss
  disc_start_for_g: 0
  disc_start_for_d: 0
  disc_loss: relative
  ssim_weight: 0
  disc_weight: 0.4
  reconstruction_loss_type: mse
  # r1, r2 loss seems not necessary
  # disc_reg_gamma: 1
  # disc_reg_type: r1r2
  # disc_reg_freq: 2
  lcr_loss_weight: 0.0
  lcr_loss_options:
    thresh: 0.75
    windows_size: [2, 2]

tokenizer:
  cfg:
    # quantizer
    quantizer_type: bsq

    # loading
    uni_path: #runs/pretrained/cosmos_f8c64_bsq/ema/tokenizer/model.safetensors
    loading_type: #pretrained

    # augmentations
    latent_noise_prob: 0.0
    use_channel_drop: false

    # qat
    quantize_to_int8: false

    # repa
    use_repa_loss: false

    bsq_flip_prob: 0.1
    bsq_group_size: 1

    model:
      latent_channels: 64
      act_checkpoint: true

  dec_cfg:
    swin_replace_levels: [1,2]
    swin_replace_mid: true
    swin_num_heads: 16
    swin_window_size: 8
    swin_shift_size: 3
    num_res_blocks: 6

ema:
  _target_: ema_pytorch.EMA
  _partial_: true
  beta: 0.999
  update_after_step: 1000
  update_every: 2
  use_foreach: true
  allow_different_devices: true
  update_model_with_ema_every: 5000

peft:
  _target_: peft.LoraConfig
  peft_type: lora
  r: 32
  lora_alpha: 8
  use_dora: false
  use_rslora: false
  target_modules:
    # [placeholder, add in tokenizer class]
    # - conv1
    # - conv2
    # - q
    # - k
    # - v
    # - proj_out
  lora_dropout: 0
  modules_to_save:
    # [placeholder, add in tokenizer class]
    # - encoder.encoder.conv_in
    # - decoder.decoder.conv_out
    # - _repa_proj
    # - encoder.quant_conv
    # - decoder.quant_conv

train:
  tokenizer_name: cosmos_bsq_lora
  proj_dir: null
  finetune_strategy: finetune_all # peft
  max_grad_norm: 1.0
  track_metrics: true
  track_metrics_duration: -1
  track_metrics_after: 0
  visualize_every: 500
  max_steps: 1_000_000
  save_every: 1_000
  grad_checkpoint: true
  seperate_enc_dec: false
  only_load_tokenizer: false
  grad_check: false
  compile_model: false
  resume_path: runs/stage1_cosmos_bsq/2026-03-12/02-39-31_nested_cosmos_f8c64p1_bsq/checkpoints/checkpoint_11
  ema_load_path:
  proxy_task_train_type: unified
  # lora specifics
  conv_in_out_reinit: false # if do not have the same channels in pretrain stage, set this to true
  add_norms: false
  save_peft_ckpts: true

  finetune_cfg:
    refine_decoder_head_n_layers: all
    adapt_latent_n_layers: 0

  tokenizer_optimizer:
    _target_: src.utilities.optim.MuonFSDP.create_muon_optimizer
    _partial_: true
    betas: ${tuple:[0.95, 0.99]}
    oned_param_algo: lion
    use_triton: true
    muon_params_defaults:
      lr: 4.0e-4
      weight_decay: 0.1
    oned_params_defaults:
      lr: 4.0e-4
      weight_decay: 0.0

  disc_optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 4.0e-4
    betas: ${tuple:[0.5, 0.9]}
    weight_decay: 1.0e-6
    eps: 1.0e-8
    foreach: true

  tokenizer_sched:
    _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 1
    reduced_factor: 2
    min_lr: 1.0e-5

  disc_sched:
    _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 1
    reduced_factor: 2
    min_lr: 1.0e-5

  log:
    run_comment: nested_cosmos_f8c64p1_bsq
    log_with_time: true
    visualize_every: 500
    log_every: 10
    log_with: []
    exp_name: bsq-lora

  debug: false

val:
  val_duration: 1000
  max_val_iters: 200 # val only `max_val_iters` batches
