hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  # tokenizer ==========
  - dataset: hyperspectral # [hyperspectral, unified_hyperspectral]
  - tokenizer: uni_cosmos_f8c16p4
  - quantizer: quant
  - accelerator: base
  - vq_loss: remote_clip_RN50
  # self ============
  - _self_

  # hydra overrides ====
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# accelerator:
#   gradient_accumulation_plugin:
#     _target_: accelerate.utils.GradientAccumulationPlugin
#     num_steps: 3

dataset:
  used: DCF_2019
  shuffle_size: 10
  num_workers: 2
  prefetch_factor: 6
  dataset_names_to_bs:
    MMSeg_YREB: 20
    DCF_2019: 16
    GID_GF2: 7
    DryadHyper: 16
    MUSLI: 7
    OHS: 9
  transform_prob: 0.5

vq_loss:
  repa_loss_weight: 1.5
  quantizer_type:
  quantizer_options:
  repa_loss_options:
    c_dim_first: true
    build_proj: false
    rgb_channels: random
    img_resize: 224 # null for no resize
    dino_img_size: 224
  disc_network_type: patchgan # [patchgan, patchgan_v2, stylegan]
  disc_ndf: 128
  use_actnorm: false
  disc_norm_type: bn2d # gn or bn? works with patchgan_v2
  disc_start_for_g: 0
  disc_start_for_d: 0
  disc_loss: hinge
  ssim_weight: 0.2
  disc_weight: 0.8
  reconstruction_loss_type: l1

tokenizer:
  hook_for_repa: true
  hook_module: decoder.decoder.mid.block_2
  act_checkpoint: false
  uni_tokenizer_path: runs/stage1_cosmos/2025-05-27_03-37-12_cosmos_f8c16p4_OHS/ema/tokenizer/model.safetensors
  loading_type: pretrained
  use_channel_drop: false
  enc_moe: false
  dec_moe: false
  norm_type: gn
  norm_groups: 32
  block_name: res_block
  # conv_in_module: resnet
  # conv_out_module: resnet
  patch_method: haar
  hidden_factor: 4
  patch_size: 4
  attn_type: none
  padding_mode: reflect # for boundary?

  latent_channels: 32

  # channel_drop_config:
  #   learnable: false
  #   drop_type: uniform_4
  #   max_channels: 16
  #   img_size: 32
  #   drop_prob: 1.0

  ## downsample and upsample
  downsample_type: ConvPixelUnshuffle
  downsample_shortcut: averaging
  upsample_type: ConvPixelShuffle
  upsample_shortcut: duplicating

ema:
  beta: 0.995
  update_after_step: 1000
  update_every: 2

train:
  tokenizer_name: uni_cosmos_f8c16p4
  proj_dir: runs/stage1_cosmos
  finetune_strategy: finetune_all # dcae_refine_decoder_head
  max_grad_norm: 0.03
  track_metrics_duration: -1
  track_metrics_after: 2000
  visualize_every: 200
  max_steps: 500_000
  save_every: 1000
  seperate_enc_dec: false
  resume_path: #runs/stage1_cosmos/2025-05-26_11-57-32_cosmos_repa_DCF_2019/checkpoints/checkpoint_20
  ema_load_path: #runs/stage1_cosmos/2025-05-27_03-37-12_cosmos_f8c16p4_OHS/ema
  only_load_tokenizer: true
  compile_model: false

  finetune_cfg:
    refine_decoder_head_n_layers: all
    adapt_latent_n_layers: 0

  tokenizer_optimizer:
    _target_: src.utilities.optim.get_muon_optimizer
    _partial_: true
    lr: 1.0e-4
    weight_decay: 0.1
    adamw_eps: 1.0e-8
    ns_diff_abc: true
    ns_norm: true

  disc_optimizer:
    _target_: src.utilities.optim.get_muon_optimizer
    _partial_: true
    lr: 1.0e-4
    weight_decay: 0.1
    adamw_eps: 1.0e-8
    ns_diff_abc: true
    ns_norm: true

  tokenizer_sched:
    # _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    # _partial_: true
    # num_warmup_steps: 1000
    # num_training_steps: ${train.max_steps}
    # num_cycles: 1
    # reduced_factor: 2
    # min_lr: 1.0e-5
    _target_: transformers.optimization.get_constant_schedule_with_warmup
    _partial_: true
    num_warmup_steps: 1000

  disc_sched:
    # _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    # _partial_: true
    # num_warmup_steps: 1000
    # num_training_steps: ${train.max_steps}
    # num_cycles: 1
    # reduced_factor: 2
    # min_lr: 1.0e-5
    _target_: transformers.optimization.get_constant_schedule_with_warmup
    _partial_: true
    num_warmup_steps: 1000

  log:
    run_comment: cosmos_f8c16p4_${dataset.used}
    log_with_time: True
    visualize_every: 500
    log_every: 10

  debug: true

val:
  val_duration: 1000
  max_val_iters: 20 # val only `max_val_iters` batches
