hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  # tokenizer ==========
  - dataset: unified_hyperspectral # [hyperspectral, unified_hyperspectral]
  - tokenizer: uni_cosmos_f8c16p4
  - quantizer: quant
  - accelerator: base
  - vq_loss: remote_clip_RN50
  # self ============
  - _self_

  # hydra overrides ====
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# accelerator:
#   gradient_accumulation_plugin:
#     _target_: accelerate.utils.GradientAccumulationPlugin
#     num_steps: 3

# dataset:
#   used: DCF_2019
#   shuffle_size: 30
#   num_workers: 2
#   prefetch_factor: 6
#   shuffle_within_workers: true
#   dataset_names_to_bs:
#     MMSeg_YREB: 20
#     DCF_2019: 16
#     GID_GF2: 7
#     DryadHyper: 16
#     MUSLI: 7
#     OHS: 9
#   transform_prob: 0.5

vq_loss:
  repa_loss_weight: 0.1
  repa_loss_options:
    c_dim_first: true
    build_proj: false
    rgb_channels: random
    img_resize: 224 # null for no resize
    dino_img_size: 224
  vf_loss_weight:
  vf_loss_options:
    c_dim_first: true
    build_proj: false
    rgb_channels: random #${dataset.rgb_channels}
    img_resize: 224
    dino_img_size: 224
    distmat_margin: 0.25
    cos_margin: 0.5
  quantizer_type:
  quantizer_options:
  disc_network_type: patchgan # [patchgan, patchgan_v2, stylegan, r3gan]
  disc_ndf: 128
  disc_num_layers: 3
  use_actnorm: false
  disc_norm_type: bn2d # gn or bn? works with patchgan_v2; bn does not support the r1, r2 loss
  disc_start_for_g: 0
  disc_start_for_d: 0
  disc_loss: relative
  ssim_weight: 0.04
  disc_weight: 0.1
  reconstruction_loss_type: mse
  # r1, r2 loss seems not necessary
  # disc_reg_gamma: 1
  # disc_reg_type: r1r2
  # disc_reg_freq: 2

tokenizer:
  hook_for_repa: true
  hook_module: decoder.decoder.mid.block_2
  proj_for_vf: false
  vf_on_z_or_module: module

  act_checkpoint: true
  uni_tokenizer_path: #runs/stage1_cosmos/2025-06-15_17-11-45_cosmos_f8c16p4_unified_hyperspectral_uni/ema/tokenizer/model.safetensors
  loading_type: #pretrained
  use_channel_drop: false
  enc_moe: false
  dec_moe: false
  norm_type: gn
  norm_groups: 32
  block_name: res_block
  moe_token_mixer_type: res_block
  # conv_in_module: resnet
  # conv_out_module: resnet
  patch_method: haar
  hidden_factor: 4
  patch_size: 1
  attn_type: none
  padding_mode: reflect # for boundary?

  latent_channels: 16
  z_channels: 16

  # channel_drop_config:
  #   learnable: false
  #   drop_type: uniform_4
  #   max_channels: 16
  #   img_size: 32
  #   drop_prob: 1.0

  ## downsample and upsample
  # downsample_type: ConvPixelUnshuffle
  # downsample_shortcut: averaging
  # upsample_type: ConvPixelShuffle
  # upsample_shortcut: duplicating

ema:
  beta: 0.995
  update_after_step: 1000
  update_every: 2

train:
  tokenizer_name: uni_cosmos_f8c${tokenizer.latent_channels}p${tokenizer.patch_size}
  proj_dir: runs/stage1_cosmos
  finetune_strategy: finetune_all # dcae_refine_decoder_head
  max_grad_norm: 0.03
  track_metrics_duration: -1
  track_metrics_after: 2000
  visualize_every: 200
  max_steps: 500_000
  save_every: 1000
  seperate_enc_dec: false
  resume_path: #runs/stage1_cosmos/2025-06-19_23-56-29_cosmos_f8c8p1_unified_hyperspectral_uni/checkpoints/checkpoint_13
  ema_load_path: runs/stage1_cosmos/2025-06-15_17-11-45_cosmos_f8c16p4_unified_hyperspectral_uni/ema
  compile_model: false
  only_load_tokenizer: false

  finetune_cfg:
    refine_decoder_head_n_layers: all
    adapt_latent_n_layers: 0

  tokenizer_optimizer:
    _target_: src.utilities.optim.get_muon_optimizer
    _partial_: true
    lr: 2.0e-4
    weight_decay: 0.1
    adamw_eps: 1.0e-8
    ns_diff_abc: true
    ns_norm: false
    # _target_: torch.optim.AdamW
    # _partial_: true
    # lr: 2.0e-4
    # weight_decay: 1.0e-4
    # eps: 1.0e-8
    # betas: [0.5, 0.95]
    # foreach: true
    # _target_: src.utilities.optim.splus.SPlus
    # _partial_: true
    # lr: 4.0e-2
    # b1: 0.5
    # b2: 0.95
    # ema_rate: 0.999
    # weight_decay: 0.01

  disc_optimizer:
    _target_: src.utilities.optim.get_muon_optimizer
    _partial_: true
    lr: 2.0e-4
    weight_decay: 0.1
    adamw_eps: 1.0e-8
    ns_diff_abc: true
    ns_norm: false
    adamw_betas: ${tuple:[0., 0.9]}  #[0.5, 0.9], gan training beta1 is zero
    # _target_: torch.optim.AdamW
    # _partial_: true
    # lr: 2.0e-4
    # weight_decay: 1.0e-4
    # eps: 1.0e-8
    # betas: [0.0, 0.9] #[0.9, 0.95]
    # foreach: true
    # _target_: src.utilities.optim.splus.SPlus
    # _partial_: true
    # lr: 2.0e-3
    # b1: 0.0
    # b2: 0.9
    # ema_rate: 0.999
    # weight_decay: 0.01

  tokenizer_sched:
    _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 1
    reduced_factor: 2
    min_lr: 1.0e-5
    # _target_: transformers.optimization.get_constant_schedule_with_warmup
    # _partial_: true
    # num_warmup_steps: 1000

  disc_sched:
    _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 1
    reduced_factor: 2
    min_lr: 1.0e-5
    # _target_: transformers.optimization.get_constant_schedule_with_warmup
    # _partial_: true
    # num_warmup_steps: 1000

  log:
    run_comment: cosmos_f8c${tokenizer.latent_channels}p${tokenizer.patch_size}_${dataset.used}_uni
    log_with_time: True
    visualize_every: 500
    log_every: 10

  debug: true

val:
  val_duration: 1000
  max_val_iters: 20 # val only `max_val_iters` batches
