hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  # tokenizer ==========
  - dataset: hyperspectral
  - tokenizer: uni_cosmos_f8c16p4_kl
  - quantizer: quant
  - accelerator: base
  - vq_loss: remote_clip_RN50
  # self ============
  - _self_

  # hydra overrides ====
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

dataset:
  used: MMSeg_YREB
  dataset_names_to_bs:
    MMSeg_YREB: 32
    DCF_2019: 12
  transform_prob: 0.5

vq_loss:
  repa_loss_weight: 1.5
  quantizer_type: null
  quantizer_options:
    # kl_weight: 1.0e-5
  repa_loss_options:
    c_dim_first: true
    build_proj: false
    rgb_channels: random
    img_resize:
    dino_img_size: 224
  disc_network_type: patchgan_v2 # [patchgan, patchgan_v2, stylegan]
  disc_ndf: 128
  use_actnorm: false
  disc_norm_type: bn2d # gn or bn? works with patchgan_v2
  disc_start_for_g: 0
  disc_start_for_d: 0
  disc_loss: hinge
  ssim_weight: 0.2
  disc_weight: 0.5
  reconstruction_loss_type: l1

tokenizer:
  hook_for_repa: true
  use_kl: false
  uni_tokenizer_path: /Data2/ZiHanCao/exps/hyperspectral-1d-tokenizer/runs/stage1_cosmos/2025-04-26_04-23-16_cosmos_pretrained_f8c16p4_repa_kl/ema/discriminator/model.safetensors
  latent_channels: 32
  z_channels: 32

ema:
  beta: 0.995
  update_after_step: 1000
  update_every: 2

train:
  tokenizer_name: cosmos_sep
  proj_dir: runs/stage1_cosmos/
  finetune_strategy: finetune_all # dcae_refine_decoder_head
  max_grad_norm: 0.03
  track_metrics_duration: -1
  track_metrics_after: 2000
  visualize_every: 200
  max_steps: 5000_000
  save_every: 500
  seperate_enc_dec: false
  resume_path:
  ema_load_path:
  only_load_tokenizer: true
  grad_check: false

  finetune_cfg:
    refine_decoder_head_n_layers: all
    adapt_latent_n_layers: 0

  tokenizer_optimizer:
    _target_: src.utilities.optim.LAMB
    _partial_: true
    lr: 8.0e-4
    betas: [0.8, 0.99]
    eps: 1.0e-8

  disc_optimizer:
    _target_: src.utilities.optim.LAMB
    _partial_: true
    lr: 8.0e-4
    betas: [0.6, 0.99]
    eps: 1.0e-8

  tokenizer_sched:
    _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 1
    reduced_factor: 2
    min_lr: 1.0e-5

  disc_sched:
    _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 1
    reduced_factor: 2
    min_lr: 1.0e-5

  log:
    run_comment: cosmos_pretrained_f8c16p4_repa_kl
    log_with_time: True
    visualize_every: 200
    log_every: 10

  debug: true

val:
  val_duration: 1000
  max_val_iters: 4 # val only `max_val_iters` batches
