hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  # tokenizer ==========
  - dataset: litdata_one_loader # [hyperspectral, unified_hyperspectral]
  - tokenizer: uni_cosmos_f8c16p1_nested # [uni_cosmos_f8c16p4, uni_cosmos_f8c16p1_nested]
  - quantizer: quant
  - accelerator: base
  - vq_loss: remote_clip_RN50
  # self ============
  - _self_

  # hydra overrides ====
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

accelerator:
  gradient_accumulation_plugin:
    _target_: accelerate.utils.GradientAccumulationPlugin
    num_steps: 1

dataset:
  train_loader:
    macro_sampled_batch_size: { 128: 12, 256: 12, 512: 6 }
    loader_kwargs:
      num_workers: 2
      batch_size: 6
      prefetch_factor: 2
      persistent_workers: true
  val_loader:
    loader_kwargs:
      num_workers: 1
      batch_size: 8
      pin_memory: false
      drop_last: true
      persistent_workers: false

vq_loss:
  # disc_in_channels: ${dataset.channels}
  # perceptual loss
  # repa loss
  repa_loss_weight: 0.1
  repa_loss_options:
    c_dim_first: true
    build_proj: false
    rgb_channels: mean
    img_resize: 512 # null for no resize
    repa_img_size: 512
    repa_model_type: dinov3
    repa_model_name: "dinov3_vitl16"
    feature_resample_type: match_teacher
    get_hier_teacher_feature: true
    loss_type: hier_distillation
    feature_normalize: spatial
  # vf loss
  vf_loss_weight:
  vf_loss_options:
    c_dim_first: true
    build_proj: false
    rgb_channels: mean #${dataset.rgb_channels}
    img_resize: 384
    repa_img_size: 384
    distmat_margin: 0.25
    cos_margin: 0.5
    repa_model_name: "dinov3_vitl16"
  # gram loss
  gram_loss_weight:
  gram_loss_options:
    c_dim_first: true
    build_proj: false
    rgb_channels: mean
    img_resize: 384 # null for no resize
    repa_img_size: 384
    repa_model_name: "dinov3_vitl16"
  # quantizer loss
  quantizer_type:
  quantizer_options:
  # discriminator loss
  disc_network_type: patchgan # [patchgan, patchgan_v2, stylegan, r3gan]
  disc_ndf: 128
  disc_num_layers: 3
  use_actnorm: false
  disc_norm_type: bn2d # gn or bn? works with patchgan_v2; bn does not support the r1, r2 loss
  disc_start_for_g: 0
  disc_start_for_d: 0
  disc_loss: relative
  ssim_weight: 0
  disc_weight: 0.4
  reconstruction_loss_type: mse
  # r1, r2 loss seems not necessary
  # disc_reg_gamma: 1
  # disc_reg_type: r1r2
  # disc_reg_freq: 2

tokenizer:
  # repa
  use_repa_loss: true
  use_vf_loss: false
  hook_module: decoder.decoder.mid.block_2
  vf_on_z_or_module: z # [z, module]
  dino_feature_dim: 1024

  # loading
  uni_path: ""
  loading_type: ""

  # augmentations
  latent_noise_prob: 0.2
  use_channel_drop: false

  # blocks
  model:
    norm_type: rmsnorm2d
    norm_groups: 32
    block_name: res_block
    moe_token_mixer_type: res_block
    hidden_factor: 4
    use_residual_factor: false

    # others
    patch_method: haar
    patch_size: 1
    attn_type: none
    padding_mode: reflect # for boundary?
    adaptive_mode: interp

    # latents
    latent_channels: 16
    z_channels: 256 # [256, 16]

    # train
    act_checkpoint: true

  channel_drop_config:
    drop_type: ${list:[4,8,12]}
    max_channels: ${tokenizer.model.latent_channels}
    drop_prob: 0.0

ema:
  _target_: ema_pytorch.EMA
  _partial_: true
  beta: 0.999
  update_after_step: 0
  update_every: 2
  use_foreach: true
  allow_different_devices: true

train:
  tokenizer_name: uni_cosmos_f8c${tokenizer.model.latent_channels}p${tokenizer.model.patch_size}_adamw_caution
  proj_dir: runs/stage1_cosmos_nested
  finetune_strategy: finetune_all # [finetune_all, decoder_only, peft]
  max_grad_norm: 3.0
  grad_checkpoint: false
  track_metrics: false
  track_metrics_duration: -1
  track_metrics_after: 2000
  visualize_every: 200
  max_steps: 1_000_000
  save_every: 1000
  resume_path: #runs/stage1_cosmos_nested/2025-12-17_18-45-37_cosmos_f8c16p1_unified_hyperspectral_adamw_caution/checkpoints/checkpoint_2
  ema_load_path: runs/stage1_cosmos_nested/2025-12-18_13-45-48_cosmos_f8c16p1_unified_hyperspectral_irepa-spatial-norm_noisy_latent_aug/ema
  compile_model: false
  only_load_tokenizer: false
  seperate_enc_dec: false

  # augmentations
  aug_pipeline_train_obj: #decoder_deg
  aug_pipeline:
    # _target_: src.stage2.denoise.utils.noise_adder.get_tokenizer_trainer_noise_adder
    # p: 0.1
    # use_torch: true

  finetune_cfg:
    refine_decoder_head_n_layers: all
    adapt_latent_n_layers: 0

  tokenizer_optimizer:
    _target_: src.utilities.optim.MuonFSDP.create_muon_optimizer
    _partial_: true
    betas: [0.9, 0.95]
    mu: 0.95
    oned_param_algo: lion
    use_triton: true
    use_preconditioned: true # turbo-muon style preconditioning
    muon_params_defaults:
      lr: 3.0e-4
      weight_decay: 0.02
    oned_params_defaults:
      lr: 3.0e-4
      weight_decay: 0.02
    # _target_: heavyball.AdamW
    # _partial_: true
    # lr: 3.0e-4
    # weight_decay: 0.02
    # caution: true
    # betas: ${tuple:[0.9,0.95]} # big model, small beta2 for stability

  disc_optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 3.0e-4
    weight_decay: 1.0e-5
    eps: 1.0e-8
    betas: [0.5, 0.9] #[0.9, 0.95]
    foreach: true

  tokenizer_sched:
    _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    _partial_: true
    num_warmup_steps: 0
    num_training_steps: ${train.max_steps}
    num_cycles: 1
    reduced_factor: 2
    min_lr: 1.0e-5
    # _target_: transformers.optimization.get_constant_schedule_with_warmup
    # _partial_: true
    # num_warmup_steps: 1000

  disc_sched:
    _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    _partial_: true
    num_warmup_steps: 0
    num_training_steps: ${train.max_steps}
    num_cycles: 1
    reduced_factor: 2
    min_lr: 1.0e-5
    # _target_: transformers.optimization.get_constant_schedule_with_warmup
    # _partial_: true
    # num_warmup_steps: 1000

  log:
    run_comment: cosmos_f8c${tokenizer.model.latent_channels}p${tokenizer.model.patch_size}_${dataset.used}_irepa-spatial-norm_noisy_latent_aug
    log_with_time: True
    visualize_every: 500
    log_every: 10
    log_with: ["swanlab"]

  debug: true

val:
  val_duration: 1000
  max_val_iters: 200 # val only `max_val_iters` batches
