hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  # tokenizer ==========
  - dataset: hyperspectral
  - tokenizer: uni_cosmos_f8c16p4
  - quantizer: quant
  - accelerator: base
  - vq_loss: remote_clip_RN50
  # self ============
  - _self_

  # hydra overrides ====
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

dataset:
  used: Apex
  prefetch_factor: 6
  num_workers: 1
  shuffle_size: -1
  loader_type: webdataset
  shuffle_within_workers: false
  # For loading the pretrained multi-channels head
  channels: ${list:[3, 4, 8, 10, 12, 13, 32, 50, 150, 175, 202, 224, 242, 368, 369, 285]}
  dataset_names_to_bs:
    MMSeg_YREB: 16
    DCF_2019: 7
    DFC_2020: 18
    GID_GF2: 12
    Houston: 7
    DryadHyper: 5
    MUSLI: 1
    OHS: 5
    WV3: 5
    QB: 5
    GF1: 5
    IKONOS: 5
    WDC: 4
    Xiongan: 4
    WHU_Hi: 6
    CD_224: 4
    CD_242: 4
    OSCD: 5

  transform_prob: 0.0

accelerator:
  gradient_accumulation_plugin:
    num_steps: 1

tokenizer:
  # repa
  use_repa_loss: true
  use_vf_loss: false
  hook_module: decoder.decoder.mid.block_2
  vf_on_z_or_module: z
  dino_feature_dim: 1024

  # loading
  uni_path: runs/stage1_cosmos/2025-09-13_17-16-19_cosmos_f8c16p1_unified_hyperspectral_latent_noise=0.0_channel_drop=False/ema/tokenizer/model.safetensors
  loading_type: pretrained

  # blocks
  model:
    norm_type: gn
    norm_groups: 32
    block_name: res_block
    moe_token_mixer_type: res_block
    hidden_factor: 4
    use_residual_factor: false

    # others
    patch_method: haar
    patch_size: 1
    attn_type: none
    padding_mode: reflect # for boundary?

    # latents
    latent_channels: 16
    z_channels: 16

    # train
    act_checkpoint: true

  channel_drop_config:
    drop_type: ${list:[4, 8, 12]}
    max_channels: ${tokenizer.model.latent_channels}
    drop_prob: 0.5

vq_loss:
  # perceptual loss
  perceptual_weight: 0.05
  repa_loss_weight: 0.02
  repa_loss_options:
    c_dim_first: true
    build_proj: false
    rgb_channels: mean
    img_resize: 512 # null for no resize
    dino_img_size: 512
    dino_name: "dinov3_vitl16"
    loss_type: am_radio
    feature_normalize: false
  vf_loss_weight:
  vf_loss_options:
    c_dim_first: true
    build_proj: false
    rgb_channels: mean #${dataset.rgb_channels}
    img_resize: 224
    dino_img_size: 224
    distmat_margin: 0.25
    cos_margin: 0.5
    dino_name: "dinov3_vitl16"
  quantizer_type:
  quantizer_options:
  disc_network_type: patchgan # [patchgan, patchgan_v2, stylegan, r3gan]
  disc_ndf: 128
  disc_num_layers: 3
  use_actnorm: false
  disc_norm_type: bn2d # gn or bn? works with patchgan_v2; bn does not support the r1, r2 loss
  disc_start_for_g: 0
  disc_start_for_d: 0
  disc_loss: relative
  ssim_weight: 0.0 # if OOM, set to 0
  disc_weight: 0.1
  reconstruction_loss_type: mse
  # r1, r2 loss seems not necessary
  # disc_reg_gamma: 1
  # disc_reg_type: r1r2
  # disc_reg_freq: 2

ema:
  beta: 0.995
  update_after_step: 1000
  update_every: 2

peft:
  _target_: peft.LoraConfig
  peft_type: lora
  r: 32
  lora_alpha: 8
  use_dora: false
  use_rslora: false
  target_modules:
    # [placeholder, add in tokenizer class]
    # - conv1
    # - conv2
    # - q
    # - k
    # - v
    # - proj_out
  lora_dropout: 0
  modules_to_save:
    # [placeholder, add in tokenizer class]
    # - encoder.encoder.conv_in
    # - decoder.decoder.conv_out
    # - _repa_proj
    # - encoder.quant_conv
    # - decoder.quant_conv

train:
  tokenizer_name: cosmos_lora
  proj_dir: runs/stage1_cosmos_lora/
  finetune_strategy: peft
  max_grad_norm: 0.03
  track_metrics_duration: -1
  track_metrics_after: 2000
  visualize_every: 200
  max_steps: 350_000
  save_every: 500
  seperate_enc_dec: false
  only_load_tokenizer: false
  grad_check: false
  track_metrics: false
  compile_model: false
  # LoRA related
  conv_in_out_reinit: true # if do not have the same channels in pretrain stage, set this to true
  add_norms: false
  save_peft_ckpts: true
  resume_path:
  ema_load_path: #runs/stage1_cosmos/2025-08-20_20-14-19_cosmos_f8c16p1_unified_hyperspectral_latent_noise=0.0_channel_drop=False/ema/tokenizer/model.safetensors

  finetune_cfg:
    refine_decoder_head_n_layers: all
    adapt_latent_n_layers: 0

  tokenizer_optimizer:
    _target_: src.utilities.optim.get_muon_optimizer
    _partial_: true
    lr: 2.0e-4
    weight_decay: 0.1
    adamw_eps: 1.0e-8
    ns_diff_abc: true
    ns_norm: false
    momentum: 0.9
    adamw_betas: ${tuple:[0.9, 0.95]} #[0.5, 0.9], gan training beta1 is zero
    adamw_wd: 0.
    # _target_: torch.optim.AdamW
    # _partial_: true
    # lr: 1.5e-4
    # weight_decay: 1.0e-4
    # eps: 1.0e-8
    # betas: [0.9, 0.995]

  disc_optimizer:
    _target_: src.utilities.optim.get_muon_optimizer
    _partial_: true
    lr: 2.0e-4
    weight_decay: 0.1
    adamw_eps: 1.0e-8
    ns_diff_abc: true
    ns_norm: false
    momentum: 0.9
    adamw_betas: ${tuple:[0.9, 0.95]} #[0.5, 0.9], gan training beta1 is zero
    adamw_wd: 0.
    # _target_: torch.optim.AdamW
    # _partial_: true
    # lr: 1.5e-4
    # weight_decay: 1.0e-4
    # eps: 1.0e-8
    # betas: [0.9, 0.995]

  tokenizer_sched:
    _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 1
    reduced_factor: 2
    min_lr: 1.0e-5

  disc_sched:
    _target_: src.utilities.train_utils.lr_scheduler.get_cosine_schedule_reduced_with_warmup
    _partial_: true
    num_warmup_steps: 1000
    num_training_steps: ${train.max_steps}
    num_cycles: 1
    reduced_factor: 2
    min_lr: 1.0e-5

  log:
    run_comment: cosmos_lora=${peft.peft_type}_r=${peft.r}_f8c${tokenizer.model.latent_channels}p${tokenizer.model.patch_size}_${dataset.used}
    log_with_time: true
    visualize_every: 200
    log_every: 10

  debug: true

val:
  val_duration: 1000
  max_val_iters: 10 # val only `max_val_iters` batches
