enc_path: "/Data4/cao/ZiHanCao/exps/Cosmos/checkpoints/Cosmos-0.1-Tokenizer-CI16x16/encoder.jit"
dec_path: "/Data4/cao/ZiHanCao/exps/Cosmos/checkpoints/Cosmos-0.1-Tokenizer-CI16x16/decoder.jit"
config:
  model:
    attn_resolutions: [32]
    channels: 128
    channels_mult: [2, 2, 4, 4]
    dropout: 0.0
    in_channels: ${dataset.channels}
    spatial_compression: 16
    num_res_blocks: 2
    out_channels: ${dataset.channels}
    resolution: 512
    patch_size: 1
    patch_method: haar
    latent_channels: 16
    z_channels: 16
    act_checkpoint: true
    model:
    norm_type: gn
    norm_groups: 32
    block_name: res_block
    moe_token_mixer_type: res_block
    hidden_factor: 4
    use_residual_factor: false
    attn_type: none
    padding_mode: reflect # for boundary?
  z_factor: 1
  use_repa_loss: true
  use_vf_loss: false
  hook_module: decoder.decoder.mid.block_2
  vf_on_z_or_module: z # [z, module]
  dino_feature_dim: 1024
