_target_: src.stage1.cosmos.cosmos_mingtok.FlowTokenizer.create_model
cfg:
  # low_level_encoder:

  # semantic_encoder:

  tokenizer:
    sampling_options_default:
      num_steps: 8
      stochasticity_ratio: 0.0
      sample_type: "transition"
      cfg_scale: 2.0

  # repa_proj:

  pixel_decoder:
    flow_type: tim
    cfg_prob: 0.5
    head_type: once
