_target_: src.stage1.two_d_vit_tokenizer.tokenizer.VITBSQModel
vitconfig:
  image_size: 256
  patch_size: 8
  width: 768
  layers: 12
  heads: 12
  mlp_ratio: 4
  drop_rate: 0.0

embed_dim: 18
embed_group_size: 9
l2_norm: True
persample_entropy_compute: "analytical"
post_q_l2_norm: True
logit_laplace: False
beta: 0.25 # commitment
