_target_: src.stage1.cosmos.cosmos_tokenizer.ContinuousImageTokenizer.create_model
model:
  attn_resolutions: [32]
  channels: 128
  channels_mult: [2, 4, 4]
  dropout: 0.0
  in_channels: ${dataset.channels}
  out_channels: ${dataset.channels}
  spatial_compression: 8
  num_res_blocks: 2
  resolution: 1024
  z_channels: 16
  act_checkpoint: true
  latent_channels: 16
  norm_type: gn
  norm_groups: 32
  block_name: res_block
  moe_token_mixer_type: res_block
  hidden_factor: 4
  use_residual_factor: false
  # others
  patch_method: haar
  patch_size: 1
  attn_type: none
  padding_mode: reflect # for boundary?
  # wrap_fsdp_last_layer: false
# repa
use_repa_loss: true
use_vf_loss: false
hook_module: decoder.decoder.mid.block_2
vf_on_z_or_module: z # [z, module]
dino_feature_dim: 1024
# loading
enc_path: ""
dec_path: ""
uni_path: ""
loading_type: null
# quant
norm_in_quant_conv: false
