cfgs:
  used: MMSeg_YREB
  batch_size_train: 32
  batch_size_val: 32
  num_workers: 2
  prefetch_factor: 6
  train_name: ${dataset.cfgs.used}_train
  val_name: ${dataset.cfgs.used}_val

dataset_paths:
  MMSeg_YREB_train: "data/MMSeg_YREB/[pansharpening_pairs,latents]/MMSeg_YREB_train_part-12_bands-MSI-{0000..0002}.tar"
  MMSeg_YREB_val: "data/MMSeg_YREB/[pansharpening_pairs,latents]/MMSeg_YREB_train_part-12_bands-MSI-0003.tar"

  wv3_train:
  wv3_val:

  qb_train:
  qb_val:

  gf2_train:
  gf2_val:

consts:
  MMSeg_YREB: 12
  wv3: 8
  qb: 4
  gf2: 4

  bands: ${dataset.consts.${dataset.cfgs.used}}

train:
  _target_: src.data.panshap_loader.get_multimodal_dataloaders
  wds_paths: ${dataset.dataset_paths.${dataset.cfgs.train_name}}
  batch_size: ${dataset.cfgs.batch_size_train}
  num_workers: ${dataset.cfgs.num_workers}
  shuffle_size: 100
  to_neg_1_1: true
  resample: true
  prefetch_factor: ${dataset.cfgs.prefetch_factor}

val:
  _target_: src.data.panshap_loader.get_multimodal_dataloaders
  wds_paths: ${dataset.dataset_paths.${dataset.cfgs.val_name}}
  batch_size: ${dataset.cfgs.batch_size_val}
  num_workers: ${dataset.cfgs.num_workers}
  shuffle_size: 100
  to_neg_1_1: true
  resample: true
  prefetch_factor: ${dataset.cfgs.prefetch_factor}
