cfgs:
  used: MMSeg_YREB
  batch_size_train: 32
  batch_size_val: 32
  num_workers: 1
  prefetch_factor: null
  train_name: ${dataset.cfgs.used}_train
  val_name: ${dataset.cfgs.used}_val

dataset_paths:
  MMSeg_YREB_train: "data/MMSeg_YREB/[pansharpening_pairs,latents]/MMSeg_YREB_train_part-12_bands-MSI-{0000..0003}.tar"
  MMSeg_YREB_val: "data/MMSeg_YREB/[pansharpening_pairs,latents]/MMSeg_YREB_train_part-12_bands-MSI-0003.tar"

  wv3_train:
  wv3_val:

  qb_train:
  qb_val:

  gf2_train:
  gf2_val:

dataset_names_to_rgb_channels:
  MMSeg_YREB: [4, 3, 2]
  DCF_2019: [5, 3, 2]
  DCF_2020: [9, 6, 3]
  GID_GF2: [3, 2, 1]
  DryadHyper: [90, 60, 40]
  Houston: [40, 20, 10]
  DFC_2020: [9, 6, 4]
  MUSLI: [66, 38, 16]
  WV3: [5, 3, 2]
  OHS: [18, 11, 6]
  QB: [2, 1, 0]
  GF1: [2, 1, 0]
  IKONOS: [2, 1, 0]

consts:
  MMSeg_YREB: 12
  wv3: 8
  qb: 4
  gf2: 4

  bands: ${dataset.consts.${dataset.cfgs.used}}
  rgb_channels: ${dataset.dataset_names_to_rgb_channels.${dataset.cfgs.used}}

train:
  _target_: src.data.panshap_loader.get_multimodal_dataloaders
  wds_paths: ${dataset.dataset_paths.${dataset.cfgs.train_name}}
  batch_size: ${dataset.cfgs.batch_size_train}
  num_workers: ${dataset.cfgs.num_workers}
  shuffle_size: 100
  to_neg_1_1: true
  resample: true
  prefetch_factor: ${dataset.cfgs.prefetch_factor}

val:
  _target_: src.data.panshap_loader.get_multimodal_dataloaders
  wds_paths: ${dataset.dataset_paths.${dataset.cfgs.val_name}}
  batch_size: ${dataset.cfgs.batch_size_val}
  num_workers: ${dataset.cfgs.num_workers}
  shuffle_size: 100
  to_neg_1_1: true
  resample: true
  prefetch_factor: ${dataset.cfgs.prefetch_factor}
