_target_: src.stage1.utilities.VQLPIPSWithDiscriminator
disc_network_type: patchgan
disc_ndf: 128
use_actnorm: false
disc_input_size: ${dataset.img_size}
disc_in_channels: ${dataset.channels}
# perceptual
perceptual_weight: 0.1
perceptual_type: resnet
perceptual_groups_to_select: null
perceptual_loss_on_logits: false
gram_model: null
gram_loss_weight: 1.0
# ssim loss
loss_ssim: true
ssim_weight: 0.1
# lecam
lecam_loss_weight: 0.001
# recon loss
reconstruction_weight: 4.0
reconstruction_loss_type: l1
force_not_use_recon_loss: false # compute the reconstruction loss outside
# gen and disc losses
gen_loss_weight: null
disc_weight: 0.02
disc_start: 0
disc_reg_r1: 10
disc_reg_freq: 0 # 0 means disabled
disc_loss: non_saturate
# quantizer
quantizer_type: null
quantizer_options:
  quantizer_loss_weight: 0.1
  codebook_enlarge_ratio: 3.0
  codebook_enlarge_steps: 2000
