train_bs: 4
val_bs: 8

# Configs
data_type: null
label_mode: seg
dataset_name: C2SMSFloodsS1

img_size: 512
num_classes: 2
ignore_index: 255
is_neg_1_1: true

consts:
  is_single_image: false
  img_size: ${..img_size}
  num_classes: ${..num_classes}
  bands: 2
  train_bs: ${..train_bs}
  val_bs: ${..val_bs}
  ignore_index: ${..ignore_index}
  is_neg_1_1: ${..is_neg_1_1}

train:
  _target_: src.stage2.segmentation.data.c2smsfloods.create_c2smsfloods_segmentation_dataloader
  data_root: data/Downstreams/c2smsfloods
  chips_dir_name: chips
  split: train
  sensor: s1
  split_unit: chip
  train_ratio: 0.7
  val_ratio: 0.15
  split_file: data/Downstreams/c2smsfloods/s1_chip_split.json
  split_seed: 1778
  crop_size: null
  resize_to: null
  random_crop: false
  batch_size: ${..consts.train_bs}
  shuffle: true
  num_workers: 4
  transform: null
  normalize: true
  normalization_strategy: baseline
  img_to_neg1_1: ${..consts.is_neg_1_1}
  s1_min_normalize: -77.0
  s1_max_normalize: 26.0
  return_name: false
  pin_memory: true
  drop_last: false

val:
  _target_: src.stage2.segmentation.data.c2smsfloods.create_c2smsfloods_segmentation_dataloader
  data_root: data/Downstreams/c2smsfloods
  chips_dir_name: chips
  split: test
  sensor: s1
  split_unit: chip
  train_ratio: 0.7
  val_ratio: 0.15
  split_file: data/Downstreams/c2smsfloods/s1_chip_split.json
  split_seed: 1778
  crop_size: null
  resize_to: null
  random_crop: false
  batch_size: ${..consts.val_bs}
  shuffle: true
  num_workers: 2
  transform: null
  normalize: true
  normalization_strategy: baseline
  img_to_neg1_1: ${..consts.is_neg_1_1}
  s1_min_normalize: -77.0
  s1_max_normalize: 26.0
  return_name: false
  pin_memory: true
  drop_last: false
